// GENERATED by sim-domain-control::fixed_pd::verilog. Do not edit.
module fixed_pd(input signed [31:0] target,position,previous,delta,kp,kd,kv,limit, output signed [15:0] duty);
wire signed [31:0] numerator = (((kp * (target - position)) + (kd * (delta - (position - previous)))) + (kv * delta));
wire signed [31:0] raw = numerator / 32'sd256;
assign duty = raw > limit ? limit : (raw < -limit ? -limit : raw);
endmodule
// Inputs must remain stable for 20 rising edges before consuming duty.
module fixed_pd_pipeline(input clk,input signed [31:0] target,position,previous,delta,kp,kd,kv,limit,output reg signed [15:0] duty);
reg signed [31:0] node_0; always @(posedge clk) node_0 <= target - position;
wire signed [31:0] node_1_a=kp, node_1_b=node_0;
reg signed [31:0] node_1_p0,node_1_p1,node_1_p2,node_1_p3,node_1_s0,node_1_s1,node_1;
always @(posedge clk) begin
node_1_p0 <= $signed({1'b0,node_1_a[7:0]})*node_1_b;
node_1_p1 <= ($signed({1'b0,node_1_a[15:8]})*node_1_b) <<< 8;
node_1_p2 <= ($signed({1'b0,node_1_a[23:16]})*node_1_b) <<< 16;
node_1_p3 <= ($signed(node_1_a[31:24])*node_1_b) <<< 24;
node_1_s0 <= node_1_p0+node_1_p1; node_1_s1 <= node_1_p2+node_1_p3; node_1 <= node_1_s0+node_1_s1;
end
reg signed [31:0] node_2; always @(posedge clk) node_2 <= position - previous;
reg signed [31:0] node_3; always @(posedge clk) node_3 <= delta - node_2;
wire signed [31:0] node_4_a=kd, node_4_b=node_3;
reg signed [31:0] node_4_p0,node_4_p1,node_4_p2,node_4_p3,node_4_s0,node_4_s1,node_4;
always @(posedge clk) begin
node_4_p0 <= $signed({1'b0,node_4_a[7:0]})*node_4_b;
node_4_p1 <= ($signed({1'b0,node_4_a[15:8]})*node_4_b) <<< 8;
node_4_p2 <= ($signed({1'b0,node_4_a[23:16]})*node_4_b) <<< 16;
node_4_p3 <= ($signed(node_4_a[31:24])*node_4_b) <<< 24;
node_4_s0 <= node_4_p0+node_4_p1; node_4_s1 <= node_4_p2+node_4_p3; node_4 <= node_4_s0+node_4_s1;
end
reg signed [31:0] node_5; always @(posedge clk) node_5 <= node_1 + node_4;
wire signed [31:0] node_6_a=kv, node_6_b=delta;
reg signed [31:0] node_6_p0,node_6_p1,node_6_p2,node_6_p3,node_6_s0,node_6_s1,node_6;
always @(posedge clk) begin
node_6_p0 <= $signed({1'b0,node_6_a[7:0]})*node_6_b;
node_6_p1 <= ($signed({1'b0,node_6_a[15:8]})*node_6_b) <<< 8;
node_6_p2 <= ($signed({1'b0,node_6_a[23:16]})*node_6_b) <<< 16;
node_6_p3 <= ($signed(node_6_a[31:24])*node_6_b) <<< 24;
node_6_s0 <= node_6_p0+node_6_p1; node_6_s1 <= node_6_p2+node_6_p3; node_6 <= node_6_s0+node_6_s1;
end
reg signed [31:0] node_7; always @(posedge clk) node_7 <= node_5 + node_6;
reg signed [31:0] raw;always @(posedge clk) begin raw <= node_7/32'sd256;duty <= raw>limit ? limit : (raw< -limit ? -limit : raw);end
endmodule
// Requires validated power-of-two gains; same shared expression graph.
module fixed_pd_power2_pipeline(input clk,input signed [31:0] target,position,previous,delta,kp,kd,kv,limit,output reg signed [15:0] duty);
reg signed [31:0] node_0; always @(posedge clk) node_0 <= target - position;
reg signed [31:0] node_1; always @(posedge clk) begin case(kp)
32'sd64: node_1 <= node_0 <<< 6;
32'sd128: node_1 <= node_0 <<< 7;
32'sd256: node_1 <= node_0 <<< 8;
32'sd512: node_1 <= node_0 <<< 9;
32'sd1024: node_1 <= node_0 <<< 10;
32'sd2048: node_1 <= node_0 <<< 11;
32'sd4096: node_1 <= node_0 <<< 12;
default: node_1 <= 0; endcase end
reg signed [31:0] node_2; always @(posedge clk) node_2 <= position - previous;
reg signed [31:0] node_3; always @(posedge clk) node_3 <= delta - node_2;
reg signed [31:0] node_4; always @(posedge clk) begin case(kd)
32'sd64: node_4 <= node_3 <<< 6;
32'sd128: node_4 <= node_3 <<< 7;
32'sd256: node_4 <= node_3 <<< 8;
32'sd512: node_4 <= node_3 <<< 9;
32'sd1024: node_4 <= node_3 <<< 10;
32'sd2048: node_4 <= node_3 <<< 11;
32'sd4096: node_4 <= node_3 <<< 12;
default: node_4 <= 0; endcase end
reg signed [31:0] node_5; always @(posedge clk) node_5 <= node_1 + node_4;
reg signed [31:0] node_6; always @(posedge clk) begin case(kv)
32'sd64: node_6 <= delta <<< 6;
32'sd128: node_6 <= delta <<< 7;
32'sd256: node_6 <= delta <<< 8;
32'sd512: node_6 <= delta <<< 9;
32'sd1024: node_6 <= delta <<< 10;
32'sd2048: node_6 <= delta <<< 11;
32'sd4096: node_6 <= delta <<< 12;
default: node_6 <= 0; endcase end
reg signed [31:0] node_7; always @(posedge clk) node_7 <= node_5 + node_6;
reg signed [31:0] raw;always @(posedge clk) begin raw <= node_7/32'sd256;duty <= raw>limit ? limit : (raw< -limit ? -limit : raw);end
endmodule
