// Adapter for live shared-Rust references; never computes motor PWM or plant physics.
export function installHardwareSync({snapshot,play,pause}) {
 const token=document.querySelector('meta[name="motor-bridge-token"]')?.content;
 if(!token||token==='__CONTROL_TOKEN__')return {onFrame(){},stop(){}};
 const box=document.createElement('div');box.className='section';box.id='hardware-sync';
 box.innerHTML=`<h3>Real motor sync</h3><p class="muted">Map three bench motors to one leg. WASD drives the live simulation; its current motor targets are sent to the FPGA.</p><label>Leg <select id="hw-leg"></select></label><div id="hw-map"></div><label>Bench motion scale <select id="hw-scale"><option value="0.03">3%</option><option value="0.05">5%</option><option value="0.09">9%</option></select></label><p><button id="hw-start" disabled>Sync motors · 12 seconds</button> <button id="hw-stop">Stop motors</button></p><p id="hw-status" role="status">Connecting…</p><div id="hw-readings"></div><p class="muted">100 Hz FPGA feedback · buffered live targets · 10% PWM ceiling · stops on pause/reset, stale simulation, lost connection, or session end. Targets are buffered about 80–160 ms ahead. Bench motion is scaled relative to the start; loaded-leg tracking is not yet validated.</p>`;
 document.querySelector('.inspector').prepend(box);
 const $=id=>box.querySelector('#'+id);let config,active=false,stopping=false,preparing=false,seq=0,latest,lastSent=-1,pending=false,serverBusy=false,sessionRun=null;
 const charts=document.createElement('section');charts.id='hardware-charts';charts.innerHTML='<div class="hw-chart-heading"><strong>Target & measured motion</strong><span><i style="color:#79aaff">━</i> Applied target &nbsp; <i style="color:#71e3ba">━</i> Real encoder</span></div><div class="hw-chart-grid"></div><small id="hw-chart-note">Connect motors to compare tracking while steering with WASD.</small>';document.querySelector('.workspace').append(charts);
 const badge=document.createElement('div');badge.id='hw-connection-banner';badge.setAttribute('role','status');badge.style.cssText='padding:10px 16px;background:#493820;color:#ffe2ab;font-weight:600';badge.textContent='Simulation only — real motors are not connected. Use Sync motors to connect.';document.querySelector('.workspace').prepend(badge);
 const chartGrid=charts.querySelector('.hw-chart-grid');
 function draw(samples,map){chartGrid.replaceChildren();for(const b of map){const values=samples.filter(s=>s.id===b.motor_id);const card=document.createElement('div');card.className='hw-chart-card';const title=document.createElement('strong');title.textContent=b.coordinate.replace('joint.','')+' · ID '+b.motor_id;card.append(title);const stats=document.createElement('small');card.append(stats);const canvas=document.createElement('canvas');canvas.width=500;canvas.height=180;card.append(canvas);chartGrid.append(card);if(!values.length){stats.textContent='Waiting for measured motion';continue;}const actual=values.map(p=>(p.telemetry.position_raw-p.home_raw)*360/4096),target=values.map(p=>(p.previous_target_counts??p.target_counts??0)*360/4096);const rms=Math.sqrt(actual.reduce((v,a,i)=>v+(a-target[i])**2,0)/values.length),sat=values.filter(p=>Math.abs(p.pwm)>=p.pwm_limit).length/values.length;stats.textContent='RMS error '+rms.toFixed(2)+'° · at drive limit '+(sat*100).toFixed(0)+'%';const ctx=canvas.getContext('2d'),bound=Math.max(0.5,...actual.map(Math.abs),...target.map(Math.abs))*1.2;ctx.fillStyle='#98aabc';ctx.font='17px system-ui';ctx.fillText('±'+bound.toFixed(1)+'°',5,18);ctx.fillText('0 s',5,175);ctx.fillText('12 s',458,175);ctx.strokeStyle='#3b4b5c';ctx.beginPath();ctx.moveTo(0,90);ctx.lineTo(500,90);ctx.stroke();for(const [data,color] of [[target,'#79aaff'],[actual,'#71e3ba']]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();data.forEach((y,i)=>{const x=values[i].frame/Math.max(1,(values[0].total_frames??120)-1)*500,py=90-y/bound*65;i?ctx.lineTo(x,py):ctx.moveTo(x,py)});ctx.stroke();}}
 charts.querySelector('#hw-chart-note').textContent='Angles relative to measured start. Errors use the previously applied target at each feedback read. '+samples.length+' real samples retained.';}
 const client=crypto.randomUUID();
 const api=async(path,body)=>{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'X-Control-Token':token,'X-Client-Id':client,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error||r.statusText);return v;};
 function stateText(s){$('hw-status').textContent=s;badge.textContent=(active?'MOTOR SYNC · ':preparing?'CONNECTING MOTORS · ':'SIMULATION ONLY · ')+s;badge.style.background=active?'#174d3c':'#493820';}
 function currentSample(){const s=snapshot();if(!s||!s.live||!s.targets?.length||s.coordinates?.length!==s.targets.length||s.done)throw Error('Reset the episode, then choose a live walking controller with named motor targets.');return {sequence:seq,time_s:s.time_s,targets_rad:Object.fromEntries(s.coordinates.map((n,i)=>[n,s.targets[i]]))};}
 function bindings(){return [...$('hw-map').querySelectorAll('[data-coordinate]')].map(row=>({coordinate:row.dataset.coordinate,motor_id:Number(row.querySelector('.hw-id').value),polarity:Number(row.querySelector('.hw-sign').value)}));}
 function save(){localStorage.setItem('walking-hardware-map-v1',JSON.stringify({leg:$('hw-leg').value,amplitude:$('hw-scale').value,bindings:bindings()}));}
 function mapping(saved){$('hw-map').replaceChildren();config.coordinates.filter(c=>c.startsWith('joint.'+$('hw-leg').value+' | ')).forEach((c,i)=>{const row=document.createElement('label');row.dataset.coordinate=c;row.style.cssText='display:flex;gap:4px;align-items:center;margin:8px 0;flex-wrap:wrap';const title=document.createElement('span');title.textContent=c.split(' | ')[1].replace(' servo output','');row.append(title);const select=document.createElement('select');select.className='hw-id';select.setAttribute('aria-label',title.textContent+' motor ID');config.ids.forEach(id=>select.add(new Option('ID '+id,id)));select.value=saved?.bindings?.[i]?.motor_id??config.ids[i];row.append(select);const sign=document.createElement('select');sign.className='hw-sign';sign.setAttribute('aria-label',title.textContent+' polarity');sign.add(new Option('+',1));sign.add(new Option('−',-1));sign.value=saved?.bindings?.[i]?.polarity??1;row.append(sign);$('hw-map').append(row)});}
 async function send(){if(!active||pending||!latest||latest.sequence<=lastSent)return;pending=true;const sample=latest;try{await api('/live/sample',sample);lastSent=sample.sequence;}catch(e){stateText(e.message);await stop('Reference transport failed');}finally{pending=false;}}
 async function stop(reason='Stopped from viewer'){if(!active&&!preparing)return;active=false;preparing=false;stopping=true;stateText(reason+' — verifying physical stop…');try{await api('/stop',{});}catch(e){stateText('Stop request unavailable; FPGA watchdog remains independent. '+e.message);}}
 $('hw-start').onclick=async()=>{try{if(serverBusy||active||preparing)return;const initial=currentSample(),map=bindings();if(new Set(map.map(b=>b.motor_id)).size!==3)throw Error('Assign a different motor ID to each joint.');save();preparing=true;stateText('Starting bounded motor session…');$('hw-start').disabled=true;latest=initial;lastSent=initial.sequence;play();await api('/live/open',{bindings:map,amplitude:Number($('hw-scale').value),source:snapshot().source,initial});active=true;preparing=false;stateText('Syncing live WASD targets…');send();}catch(e){preparing=false;active=false;stateText(e.message);pause();}};
 $('hw-stop').onclick=()=>{stop('Operator stop');pause()};$('hw-leg').onchange=()=>{mapping();save()};$('hw-map').onchange=save;$('hw-scale').onchange=save;
 async function poll(){try{const s=await api('/status');serverBusy=s.active;$('hw-start').disabled=!config||serverBusy||active||preparing||stopping;for(const el of box.querySelectorAll('select'))el.disabled=serverBusy||active||preparing;
  if(active||stopping){sessionRun=s.run;const samples=s.samples??[];draw(samples,bindings());if(samples.length){const lines=bindings().map(b=>{const p=samples.filter(p=>p.id===b.motor_id).at(-1);if(!p)return 'ID '+b.motor_id+': waiting';return 'ID '+b.motor_id+': '+((p.telemetry.position_raw-p.home_raw)*360/4096).toFixed(2)+'° · '+p.telemetry.voltage_v.toFixed(1)+' V · '+p.telemetry.temperature_c+' °C'+(p.live_source?' · input age '+(p.live_source[2]*1000).toFixed(0)+' ms':'');});$('hw-readings').textContent=lines.join('\n');$('hw-readings').style.whiteSpace='pre-line';}
   if(!s.active&&!preparing){active=false;stopping=false;pause();stateText((s.result?.result?.stop_verified?'Motors stopped and verified. ':'Stop verification incomplete. ')+(s.result?.result?.failure??s.result?.error??(s.result?.completed?'12-second live session complete.':'Motor session ended without completion.'))+' Saved: '+sessionRun);}
  }
 }catch(e){if(active||preparing){stop('Bridge disconnected');pause()}else stateText(e.message)}setTimeout(poll,150)}
 api('/config').then(c=>{config=c;[...new Set(c.coordinates.map(c=>c.replace('joint.','').split(' | ')[0]))].forEach(l=>$('hw-leg').add(new Option(l,l)));let saved;try{saved=JSON.parse(localStorage.getItem('walking-hardware-map-v1'))}catch{}if(saved){$('hw-leg').value=saved.leg;$('hw-scale').value=saved.amplitude;}mapping(saved);draw([],bindings());stateText('Ready. Choose a leg, then start sync and steer with WASD.');poll()}).catch(e=>stateText(e.message));
 setInterval(send,50);window.addEventListener('pagehide',()=>stop('Page closed'));
 return {onFrame(){try{seq++;latest=currentSample();}catch(e){if(active){stop(e.message);pause()}}},stop};
}
