import fs from'node:fs';import assert from'node:assert/strict';
const here=import.meta.dirname,read=n=>JSON.parse(fs.readFileSync(`${here}/${n}.json`));
const prefix=process.argv[2]||'baseline',native=read(prefix+'.native'),profile=read(prefix+'.profiled'),wasm=read(prefix+'.wasm');
const fields=['joint_positions','joint_velocities','motor_states','servo_states','servo_commands','servo_targets_rad','motor_readings','driver_readings','poses','contacts'];
function differences(a,b){const max={};function walk(x,y,p){if(typeof x==='number'){assert(Number.isFinite(x)&&Number.isFinite(y));max[p.split('.')[0]]=Math.max(max[p.split('.')[0]]||0,Math.abs(x-y));}else if(Array.isArray(x)){assert.equal(x.length,y.length,p);x.forEach((v,i)=>walk(v,y[i],p+'.'+i));}else if(x&&typeof x==='object'){assert.deepEqual(Object.keys(x).sort(),Object.keys(y).sort(),p);for(const k of Object.keys(x))walk(x[k],y[k],p+'.'+k);}else assert.equal(x,y,p);}
 assert.equal(a.frames.length,b.frames.length);for(let i=0;i<a.frames.length;i++){assert.equal(a.frames[i].time_s,b.frames[i].time_s);for(const key of fields)walk(a.frames[i][key],b.frames[i][key],key);}return max;}
const timerParity=differences(native,profile);assert(Object.values(timerParity).every(v=>v===0),'profiling changed physics');
const parity=differences(native,wasm);const stats=r=>{const t=[...r.transition_wall_s].sort((a,b)=>a-b);return {wall_s:r.wall_s,simulation_per_wall:r.frames.at(-1).time_s/r.wall_s,step_p50_s:t[Math.floor(t.length*.5)],step_p95_s:t[Math.ceil(t.length*.95)-1],maximum_step_s:t.at(-1),complete:r.frames.at(-1).time_s===3&&!r.error};};
const p=read(prefix+'.profile');const report={native:stats(native),wasm:stats(wasm),wasm_to_native_speedup:wasm.wall_s/native.wall_s,profile_unchanged:timerParity,native_wasm_max_abs:parity,profile_buckets:p.buckets.filter(b=>b.seconds>0).sort((a,b)=>b.seconds-a.seconds),scope:'Three seconds, identical seed/inputs/physical recipe. Profile buckets nest and must not be summed. Timing excludes initialization/final file serialization.'};
fs.writeFileSync(`${here}/${prefix}.comparison.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
