import fs from 'node:fs';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const d='examples/full-robot/speed-ceiling',out='runs/speed-ceiling/viewer',profile='synchronized-human-5ms',id='physics-fast-wasd';
const read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
fs.mkdirSync(out,{recursive:true});
fs.mkdirSync(`${out}/data`,{recursive:true});
let r=spawnSync('tar',['-xzf','examples/full-robot/gait-exploration/browser-template.tar.gz','-C',out]);if(r.status!==0)throw Error('template extraction failed');
for(const file of ['viewer.js','motion-commands.mjs'])fs.copyFileSync(`web/viewer/${file}`,`${out}/${file}`);
for(const file of ['worker.js','worker-message.mjs'])fs.copyFileSync(`web/${file}`,`${out}/${file}`);
const wasm='/Users/elliot/physics-simulator/target/gait-exploration/wasm32-unknown-unknown/release/sim_web.wasm';
r=spawnSync('/Users/elliot/.cargo/bin/wasm-bindgen',[wasm,'--target','web','--out-name','sim_web','--out-dir',out],{stdio:'inherit'});if(r.status!==0)throw Error('WASM binding failed');
const paths=[`runs/speed-ceiling/validation/${profile}.scene.json`,`runs/speed-ceiling/validation/${profile}.config.json`,`examples/full-robot/fast-wasd/task.json`],data={scene:read(paths[0]),config:read(paths[1]),task:read(paths[2]),seed:0};
const path=`data/${id}.json`;fs.writeFileSync(`${out}/${path}`,JSON.stringify(data)+'\n');
const entry={id,label:'Experimental · Fast WASD gait · 100 mm/s command',mode:'embedded',path,task:paths[2],motion_commands:['command.forward_speed','command.lateral_speed','command.yaw_rate'],motion_heartbeat:'command.packet_sequence',asset_sha256:hash(`${out}/${path}`),description:'Hold W/S for forward/reverse and combine with A/D to steer. Release to finish the foot transfer and brake. Walking turns; no pivot turn.',readiness:'60-second motion checks passed. Brief stance contact losses remain under review. Browser 0.45× realtime / 110 ms p95; hardware transfer is unvalidated.',evidence:'60 s at 0.625 ms: 100.4–102.7 mm/s, 4.3% loaded-foot slip. Release stopped within 0.42 s / 23 mm. Frozen commands stopped within 0.60 s / 43 mm. Provisional actuator model and ideal joint observations.'};
fs.writeFileSync(`${out}/catalog.json`,JSON.stringify({presets:[entry]},null,2)+'\n');
fs.writeFileSync(`${out}/leaderboard.json`,JSON.stringify({version:1,entries:[],scope:'Isolated development bundle; measurements are retained in examples/full-robot/speed-ceiling. No ranked controller claim.'},null,2)+'\n');
const inputs=[...paths,'Cargo.lock','crates/sim-domain-robot/src/sdf.rs','crates/sim-domain-robot/src/model.rs','crates/sim-domain-control/src/command_lease.rs','crates/sim-script/src/lib.rs','web/viewer/viewer.js','web/viewer/motion-commands.mjs',`${d}/package_browser.mjs`];
const manifest={version:1,profile,wasm:{artifact_sha256:hash(wasm),browser_module_sha256:hash(`${out}/sim_web_bg.wasm`)},inputs:Object.fromEntries(inputs.map(p=>[p,hash(p)])),scope:'Fresh shared Rust/WASM runtime with CAD grid refinements and command lease. Simulation time and commands recorded for replay. Browser measurements are separate from native physical acceptance.'};
fs.writeFileSync(`${out}/build-manifest.json`,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(`${d}/browser-manifest.json`,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(`${d}/browser-preset.json`,JSON.stringify(entry,null,2)+'\n');
fs.writeFileSync(`${out}/OPEN.txt`,'Experimental fast WASD gait. Start the server with node serve-viewer.mjs . 4173, then open http://127.0.0.1:4173/?preset=physics-fast-wasd. W/S translate; combine with A/D to steer. Release finishes the transfer and brakes. Not a deployed hardware controller.\n');
console.log(out);
