//! Robot mode's REST commands: the registry's spec table and the
//! conversion of a REST command ([`wire::Command`]) into [`RobotAction`].
use super::*;
use crate::app::actions::{Spec, spec};
use crate::robot::motion::KEYS;

impl actions::Action for RobotAction {
    fn commands() -> Vec<Spec> {
        fn c(name: &'static str, example: Value, description: &str) -> Spec {
            spec(name, actions::ROBOT, example, description)
        }
        vec![
            c("robot_state", json!({}), "Read-only robot mode: file, workspace (the resolved root: root, found_by override | env | opened_file | cwd, from, error, rule; also in GET /v1/capabilities), status (loading | loaded | error, with the error naming the path), link_count, links, the selected link (mass, com, inertia, material and its density or material_in_file=false, file_notes), joints, motors, transmissions, battery, actuator_profiles (with content hashes), uncertainty, identification, the source block verbatim (the export's own `source`), source_file (--robot FILE's path, sha256, loaded_at, reload_count, watching, last_reload, run_reset; see robot_reload; watching=false for a preset), notice (the last reload's result), and cad_link (current | stale | missing | no_recorded_hash | no_source_file | unreadable, with the resolution rule and paths tried). Numbers are full-precision JSON; provenance is null unless the file carries a typed label (provenance_rule). format {version, name, …} names the loaded generation: physical v<N> (PhysicalModel; N is the file's version, 3 or later), or for a planar v2 file `planar v2 summary` with fidelity (robot_planar::FIDELITY, verbatim) and the planar build's warnings; a planar file also reports planar {unit, plane, source, bodies, joints (simulated or not), selected_body, selected_joint, frame (time, joint angles and targets, body poses, chain tips), frame_axes, jog_rule}, run from its own run thread, and unavailable (every refused action with its reason), with the v3-only blocks null. Also the inspector section and scroll, run (null until loaded; phase idle with null time before any build; see robot_run), and overlays (--robot FILE run-thread contacts, joint frames and deflections with flags, counts, samples and scales, and overlays.stress for the read-only .simresult.json; available=false with the reason for presets; see robot_overlay). Nothing is written."),
            c("system_ui", json!({"action":{"operation":"controls"}}), "Discover the link list, inspector sections (section:link | joints | drives | source), inspector scrolling and view controls, the run controls (run:start | pause | step | reset, and run:speed_down | run:speed_up | run:speed:<scale>: the same RobotAction::Speed as robot_speed), robot:reload and overlay:contacts | overlay:joints | overlay:deflections | overlay:stress for --robot FILE (the same RobotAction::Reload as robot_reload and RobotAction::Overlay as robot_overlay; overlay controls are listed for presets but disabled with the reason), and for a preset the run, motion, recording, replay and gait preview controls (gait:open:<report>, gait:play, gait:pause, gait:stop, gait:seek:0 | - | + (±period/12 from the latest pose), gait:speed:0.25 | 0.5 | 1, gait:list: the same RobotAction::Gait as REST robot_gait), and for a recorded preset the timeline controls recorded:start | recorded:step- | recorded:play | recorded:pause | recorded:step+ | recorded:speed:<scale> (the same RobotAction::Recorded as REST robot_recorded) (controls) and activate one by id with the current ui_revision (activate), through the same handler as a click. Selection is shared by the list, the 3D view and robot_state."),
            c("robot_jog", json!({"joint":"left axle","target":0.5}), &format!("Servo-target jog of one joint by its file name: {JOG_LABEL}. Give target (absolute; rad, or m on a prismatic joint) or delta (from the current requested target). The same handler as the jog +/− buttons and system_ui jog:<joint>:+/- controls (±{JOG_STEP_RAD} rad, ±{JOG_STEP_M} m prismatic; listed for the joints touching the selected link). Errors name the joint: unknown joint, no servo target (passive joint, firmware none, fixed, or a trajectory-mode file), non-finite target, or a target outside the file's limits (with the limit; never clamped); after a failed run, Reset first. {JOG_SEMANTICS} robot_state.jog reports control mode, label and, per joint, the limit (or no limit in file), requested target, and the target and measured value from the latest accepted frame. For a planar v2 file: {}", planar::JOG_RULE)),
            c("robot_run", json!({"action":"start"}), "Run controls, the same handler as the Run/Pause/Step/Reset buttons and system_ui run:* controls. start runs the shared PhysicalRobot on the run thread (built from the loaded model with sim_runtime::registry() and BuildOptions::default()), paced at most to speed_scale × real time (robot_speed; default ×1); pause stops it; step advances exactly one 0.02 s chunk and is refused while running; reset rebuilds at t = 0 (assembly pose), bumps the generation and leaves it paused (allowed after a failure). A planar v2 file runs on its own thread (robot-run (planar v2)) through sim-phenomena's shared planar build (cad_robot::build_planar), built at open and paused at t = 0; start/pause/step/reset act on it the same way (reset rebuilds from the loaded model; Reload re-reads the file), and an advance error stops it with the error verbatim (robot_planar::PACING for its pacing; keys Space and R as well). An unknown action is an error naming it and listing the valid ones. robot_state.run reports phase (idle | building | running | paused | failed), time, steps (chunks), chunk_s, measured rtf, speed_scale (requested) and compute_limited, generation, error and the latest accepted frame. Nothing is written."),
            c("robot_speed", json!({"scale":4}), &format!("Set the run speed scale (× real time) for --robot FILE runs, preset runs and replays alike: scale one of {} (powers of two; anything else is refused naming the allowed values, never clamped), or action up | down alone (refused at ×8 / ×0.125, naming the limit). The same RobotAction::Speed as keys =/+ and − (numpad too), the header −/×scale/+ buttons (×scale resets to ×1) and system_ui run:speed_up | run:speed_down | run:speed:<scale>. Allowed in every phase; it applies from the next chunk (or the next Run) and survives Reset and a file reload. Pacing only: dt, chunk_s and the physics step are unchanged. {} robot_state.run reports speed_scale (requested), rtf (achieved) and compute_limited: {}. A planar v2 file takes the same scales for its own pacing: {}", SPEED_SCALES.map(|s| s.to_string()).join(", "), run::PACING, run::COMPUTE_LIMITED_RULE, planar::PACING)),
            c("robot_recorded", json!({"action":"seek","t":0.8}), &format!("Recorded-preset timeline ({}): action play | pause | start alone, seek with t (recorded time, s), step with delta (+1 | -1) or speed with scale. The same RobotAction::Recorded as the inspector Recorded buttons (Start, Step −1, Play, Pause, Step +1) and system_ui recorded:start | recorded:step- | recorded:play | recorded:pause | recorded:step+ | recorded:speed:<scale>. One playback worker (not the UI thread) owns the pre-mapped frames, runs the clock and publishes generation-stamped frames; the lookup is {}. {} {} {} {} speed accepts exactly one of {} (the run speed scales, never clamped) and is the same scale as robot_speed and the header −/×/+ buttons, which drive this playback for a recorded preset. Refused naming the reason: a non-recorded view (an embedded preset or --robot FILE), a non-finite or out-of-range t, a step at either end or not ±1, play while playing, pause while not playing. The response returns at once; robot_state.recorded reports label, preset, scene/capture paths, frame_count, first/last_time_s, duration_s, time_s, frame_index, frame_time_s, speed, phase (playing | paused | ended), generation, frame_generation and pending (a command not yet applied by the worker), description, readiness and evidence verbatim from presets.json, meta (the capture's source fidelity/cad_sha256/file/cad_revision, completed, error, simulated_s, stepping_wall_s, step_s, completed_steps, requested_steps as read; absent ones null and listed in absent), recorded_rate, unmatched_capture_links and the rules. Nothing is simulated.", crate::robot::preset::RECORDED_LABEL, sim_runtime::embedded_capture::LOOKUP_RULE, playback::CLOCK_RULE, playback::SEEK_RULE, playback::STEP_RULE, playback::START_RULE, SPEED_SCALES.map(|s| s.to_string()).join(", "))),
            c("robot_presets", json!({}), &format!("List the robot presets declared in {} (its paths resolved against the workspace root, reported in workspace): id, label, mode, scene/config/task paths, inputs_exist and missing, under_ignored_runs, capture, runs_as (EmbeddedEnvironment with a task, else EmbeddedSession; recorded playback for mode `recorded`) and openable with the reason when not (the build itself is not attempted): {}. Mode `embedded` runs natively; mode `recorded` plays back its capture (no physics).", crate::robot::preset::PRESETS, crate::robot::preset::OPENABLE_RULE)),
            c("robot_preset", json!({"id":"robot-measured-400hz"}), "Open a declared embedded or recorded preset by id. A recorded preset (mode `recorded`, a scene and a capture, e.g. robot-lift-5mm) reads its scene and its *-execution.json capture on the loader thread with the shared sim_runtime::embedded_capture reader, maps every frame to the scene's links by name and shows frame 0; robot_state.preset reports frame_count, duration_s, the capture's metadata as written (absent fields null), unmatched_capture_links and load_seconds; no physics is built, and run, jog, motion, save recording, replay, gait preview and overlays are refused naming the preset. An embedded preset opens in this window (replacing the current robot and stopping its run thread). Unknown ids, other modes and missing inputs are refused naming the id. The scene, config and task are parsed exactly as declared on a worker thread; scene.robot is drawn and inspected through the same loader as --robot FILE. Run/Pause/Step/Reset (robot_run) then drive the shared EmbeddedEnvironment (task) or EmbeddedSession (no task) on the run thread with seed 0 (recorded), one action interval or clamp(report_every, 1, 40) nominal steps per chunk. robot_state.preset reports id, label, paths, readiness and evidence verbatim, seed, step_s, chunk and step counts; run.phase `ended` with run.end reports a reached horizon or a terminated/truncated episode. Servo-target jog is not offered for presets."),
            c("robot_input", json!({"channels":{"command.forward_speed":0.001}}), &format!("Motion request for a running robot preset: {}. Give channels (values by motion channel name; the other motion channels keep their requested values) or key (w | a | s | d latches that key's request until stop, another key or a channel request; stop sets every motion channel to 0). The same handler as physical W/A/S/D (press/release) and X (stop), the W/A/S/D/Stop buttons and system_ui motion:w|a|s|d|stop. Motion channels come from the session's policy_contract.step_reference.config, else the preset's presets.json motion_commands (as web/viewer/motion-commands.mjs); key vectors from motion_key_vectors, else the channel bounds. Refused naming the channel and its bounds: an unknown channel, a session input that is not a motion channel, a non-finite value, or a value or summed key vector outside the channel's bounds ({}). Also refused, naming the reason: --robot FILE, a preset with no motion config, no built session (Run or Step builds it), a failed or ended run, an exhausted heartbeat. A declared motion_heartbeat is {} robot_state.motion reports source, channels with bounds, requested and held values, active keys, heartbeat, last refusal and the label.", motion::LABEL, motion::CLAMP_RULE, motion::HEARTBEAT_RULE)),
            c("robot_save_recording", json!({"note":"after motion:w"}), &format!("Save the loaded preset run's recording: the same handler as the Save recording button and system_ui recording:save. The run thread snapshots the shared recording (EmbeddedEnvironment::episode_recording() for a preset with a task, EmbeddedSession::recording() without, as the browser's Download) in any phase with a built session, running, paused, ended or failed; a writer thread writes it, so the response returns at once with recording.pending set and robot_state.recording.last_saved {{path, meta_path, kind, version, completed_steps, replayable, not_replayable_reason, failure, saved_utc, bytes}} (or recording.error) once written. Optional path (relative to the root or absolute) and note (kept in the sidecar). {} {} {} Refused, naming the reason: --robot FILE, no built session (Run or Step first), a save still being written, a path under examples/, cad/ or web/, a name not ending in .json or ending in .meta.json, and an existing file (reported in recording.error).", recording::LOCATION_RULE, recording::FILE_RULE, recording::REPLAYABLE_RULE)),
            c("robot_gait", json!({"report":"6216-Bayesian-009-472d11d4"}), &format!("Kinematic gait preview on the loaded preset: {}. Open a gait with report (a name in robot_state.gait_preview.reports: {}) or path (a compiled.json, relative to the workspace root or absolute); then {{\"action\":\"play\"}}, pause, stop, list, {{\"action\":\"seek\",\"t\":0.5}} (gait time, s) or {{\"action\":\"speed\",\"scale\":0.5}} (0 < scale <= 1). One worker reads the gait with sim_runtime::gait_playback::compiled_with_governor (governor from detailed.spec.json, else spec-identity.json, else none) and Gait::from_compiled, samples it ({}) and poses the scene with the shared KinematicMirror at lift {} m (web/viewer/calibration-mirror.mjs). Refused naming the reason: --robot FILE (no scene), a missing file (named), an unknown report, a gait joint that is not a coordinate of the preset's scene (named), a mirror that cannot serve the scene, a running physics run or a replay in progress; Run, Step and Replay are refused while a gait is loaded. Load errors after the command returns land in robot_state.gait_preview.error, with any previous preview kept. robot_state.gait_preview reports label, phase (idle | loading | playing | paused | failed), generation and frame_generation, report, compiled, governor_source, period_s, nominal_speed_m_s, report_speed_m_s, status and fidelity (the report's, verbatim), gait_time_s, speed_scale, desired_rad and commanded_rad by joint, drives, lift_m, authored_limit_violations and solve_ms. Nothing is simulated, written or sent to hardware.", gait::LABEL, gait::LISTING_RULE, gait::SAMPLING_RULE, gait::LIFT_M)),
            c("robot_replay", json!({"file":"20260930T060822.729Z.json"}), &format!("Replay a saved recording of the loaded preset: the same handler as the inspector Replay buttons and system_ui replay:<file>. Give file (a bare name listed in robot_state.recordings.files, in runs/robot-presets/<preset-id>/) or path (any readable recording .json, relative to the root or absolute; reading is not restricted). {{\"action\":\"cancel\"}} stops the replay between chunks (system_ui replay:cancel); {{\"action\":\"list\"}} lists the recordings again off the UI thread (system_ui replay:refresh). {} {} {} {} robot_state.replay reports path, phase (idle | replaying | cancelled | done | failed), completed/total with unit, completed_steps and recorded_completed_steps, verdict, error, measured, replaced and sidecar. Refused, naming the reason: --robot FILE, a replay already in progress, a running run (Pause first), a building session, a missing or non-.json file, a recording of the other kind, a runtime mismatch (the runtime's message) and a session identity mismatch (the viewer's labelled check).", recording::REPLAY_RULE, recording::VERDICT_RULE, recording::IDENTITY_RULE, recording::MEASURED_RULE)),
            c("robot_reload", json!({}), &format!("Re-read the opened --robot FILE now: the same RobotAction::Reload as the watch, the header Reload button and system_ui robot:reload. {} Returns at once; the result lands in robot_state.source_file {{path, sha256 (of the displayed model's bytes), loaded_at (UTC), reload_count (successful reloads), unchanged_checks, watching, in_flight, last_reload {{trigger watch | manual, outcome loaded | unchanged | failed, error naming the path, at (UTC)}}, run_reset, showing_last_good, failing_error}} and robot_state.notice. A loaded reload replaces the model, meshes, link list, notes and cad_link, keeps the selected link by name (else clears it with a note), discards any run or jog and spawns a fresh idle run thread whose generation is the old one + 1 (robot_state.run.generation; graphs clear by the generation rule); a planar v2 file whose run was running starts again from t = 0 once rebuilt. Refused naming the reason: a preset, a load or reload already in flight. (robot_state.source is still the file's own export source block.)", source::RULE)),
            c("robot_overlay", json!({"contacts":true,"joints":true,"deflections":false,"stress":true}), &format!("Show or hide the --robot FILE overlays. stress (key H, system_ui overlay:stress; default off) colours the link meshes per vertex from the model's read-only .simresult.json through sim_domain_robot::stress_results ({}); robot_state.overlays.stress reports enabled, painting, path, mtime_unix_s and mtime_utc, status (current | stale | no recorded hash | no results file | invalid results file), recorded_physical_hash, model_physical_hash, peak_stress_pa per link, hotspot_links, error, absent and paint_seconds. {} Run-thread overlays: contacts (spheres at PhysicalRobot::contacts points with force lines at {} m/N; red on the ground, orange against another link), joints (PhysicalRobot::joint_frames: a white sphere and each axis drawn ±{} m in yellow, cyan, magenta) and deflections (PhysicalRobot::deflections: flexible-link boundary displacement lines magnified ×{}). Give any subset; the others keep their values. The same RobotAction::Overlay as keys C / J / F / H, the inspector overlay buttons and system_ui overlay:contacts | overlay:joints | overlay:deflections | overlay:stress. Run-thread defaults: all on. A planar v2 file draws only contacts (its chain-tip contact points, red dots); turning joints, deflections or stress on is refused naming why (they need a v3 export). {} Drawn in the model frame through RobotRoot's transform (the link meshes' parent), only from the latest accepted frame of the current generation. robot_state.overlays reports flags, frame_flags, frame_generation, frame_time, contacts {{count, sample: first {} of link, other (link name | ground), point, force, penetration}}, joints {{count, sample}}, deflections {{count, max_displacement_m}} and scales. Refused for presets (their session frames publish no contacts, joint frames or deflections, and a preset has no results file).", sim_domain_robot::stress_results::SCALE, stress::RULE, run::FORCE_SCALE_M_PER_N, run::JOINT_AXIS_HALF_M, run::DEFLECTION_MAGNIFICATION, run::OVERLAY_COST_RULE, run::OVERLAY_SAMPLE)),
            c("state", json!({}), "Robot mode: {robot_state (as robot_state), viewer_mode}"),
            c("camera", json!({"focus":[0,0,0],"radius":0.5,"yaw":0.7,"pitch":0.4}), "Absolute orbit in the display frame (Y up); SI metres and radians"),
            c("fit", json!({}), "Fit the robot"),
        ]
    }
    fn controls() -> &'static [&'static str] {
        &[
            "link:<index>", "clear_selection", "section:<section>", "inspector:scroll_down", "inspector:scroll_up", "fit", "robot:reload", "graphs:toggle", "overlay:<kind>",
            "run:<action>", "run:speed_down", "run:speed_up", "run:speed:<scale>", "recorded:<transport>", "recorded:speed:<scale>", "jog:<joint>:-", "jog:<joint>:+",
            // A planar (v2) file: the arrow keys' joint (jog ids there are by built joint index).
            "joint:<index>",
            "motion:w", "motion:a", "motion:s", "motion:d", "motion:stop", "recording:save", "replay:<file>", "replay:cancel", "replay:refresh",
            "gait:open:<report>", "gait:play", "gait:pause", "gait:stop", "gait:seek:<step>", "gait:speed:<scale>", "gait:list",
            // The Leg calibration panel's controls (hardware::panel::controls), passed on to its handler.
            "hardware:<name>",
        ]
    }
}

/// A REST command as its action (the checks that need no view, with the
/// errors they always gave).
impl TryFrom<wire::Command> for RobotAction {
    type Error = String;
    fn try_from(command: wire::Command) -> Result<Self, String> {
        use wire::Command as W;
        Ok(match command {
            W::State => RobotAction::State,
            W::RobotState => RobotAction::RobotState,
            W::SystemUi { action: wire::Ui::Controls } => RobotAction::Controls,
            W::SystemUi { action: wire::Ui::Activate { id, ui_revision } } => RobotAction::Activate { id, ui_revision },
            W::Camera { focus, radius, yaw, pitch } => RobotAction::Camera { focus, radius, yaw, pitch },
            W::Fit => RobotAction::Fit,
            W::RobotRun { action } => RobotAction::Run { action: RunAction::parse(&action)? },
            W::RobotJog { joint, target, delta } => match (target, delta) {
                (Some(target), None) => RobotAction::JogTo { joint, target },
                (None, Some(delta)) => RobotAction::Jog { joint, delta },
                _ => return Err("robot_jog needs exactly one of target (absolute, rad or m) or delta".into()),
            },
            W::RobotPresets => RobotAction::Presets,
            W::RobotPreset { id } => RobotAction::OpenPreset { id },
            W::RobotInput { channels, key } => {
                let request = match (channels, key.as_deref()) {
                    (Some(map), None) => MotionRequest::Channels(map),
                    (None, Some("stop")) => MotionRequest::Stop,
                    (None, Some(k)) => match k.chars().collect::<Vec<_>>()[..] {
                        [c] if KEYS.contains(&c) => MotionRequest::Key(c),
                        _ => return Err(format!("robot_input key `{k}` is not one of w, a, s, d, stop")),
                    },
                    _ => return Err("robot_input needs exactly one of channels ({\"<motion channel>\": value, …}) or key (w | a | s | d | stop)".into()),
                };
                RobotAction::Motion { request }
            }
            W::RobotSaveRecording { path, note } => RobotAction::SaveRecording { path, note },
            W::RobotReplay { file, path, action } => match (action.as_deref(), file.is_some() || path.is_some()) {
                (None | Some("start"), _) => RobotAction::Replay { file, path },
                (Some("cancel"), false) => RobotAction::CancelReplay,
                (Some("list"), false) => RobotAction::RefreshRecordings,
                (Some(a @ ("cancel" | "list")), true) => return Err(format!("robot_replay action `{a}` takes no file or path")),
                (Some(a), _) => return Err(format!("unknown robot_replay action `{a}`; valid actions: start (default, with file or path), cancel, list")),
            },
            W::RobotGait { action, report, path, t, scale } => {
                let action = match (action.as_deref(), report, path, t, scale) {
                    (None | Some("open"), Some(r), None, None, None) => GaitAction::Open { source: GaitSource::Report(r) },
                    (None | Some("open"), None, Some(p), None, None) => GaitAction::Open { source: GaitSource::Path(p) },
                    (Some("seek"), None, None, Some(t), None) => GaitAction::Seek { t },
                    (Some("speed"), None, None, None, Some(scale)) => GaitAction::Speed { scale },
                    (Some("play"), None, None, None, None) => GaitAction::Play,
                    (Some("pause"), None, None, None, None) => GaitAction::Pause,
                    (Some("stop"), None, None, None, None) => GaitAction::Stop,
                    (Some("list"), None, None, None, None) => GaitAction::List,
                    (a, ..) => return Err(format!("robot_gait {}: give exactly one of report or path (open, the default), or action seek with t, speed with scale, or play | pause | stop | list alone", a.map_or("open".into(), |a| format!("action `{a}`")))),
                };
                RobotAction::Gait { action }
            }
            W::RobotReload => RobotAction::Reload { trigger: ReloadTrigger::Manual },
            W::RobotOverlay { contacts: None, joints: None, deflections: None, stress: None } => return Err("robot_overlay needs at least one of contacts, joints, deflections, stress (true | false)".into()),
            W::RobotOverlay { contacts, joints, deflections, stress } => RobotAction::Overlay { contacts, joints, deflections, stress },
            W::RobotSpeed { action, scale } => {
                let speed = match (action.as_deref(), scale) {
                    (None | Some("set"), Some(scale)) => SpeedRequest::Set { scale },
                    (Some("up"), None) => SpeedRequest::Up,
                    (Some("down"), None) => SpeedRequest::Down,
                    (a, _) => return Err(format!("robot_speed {}: give scale (one of {}) or action up | down alone", a.map_or("without scale".into(), |a| format!("action `{a}`")), SPEED_SCALES.map(|s| s.to_string()).join(", "))),
                };
                RobotAction::Speed { speed }
            }
            W::RobotRecorded { action: name, t, scale, delta } => {
                let action = match (name.as_str(), t, scale, delta) {
                    ("play", None, None, None) => RecordedAction::Play,
                    ("pause", None, None, None) => RecordedAction::Pause,
                    ("start", None, None, None) => RecordedAction::Start,
                    ("seek", Some(t), None, None) => RecordedAction::Seek { t },
                    ("step", None, None, Some(delta)) => RecordedAction::Step { delta },
                    ("speed", None, Some(scale), None) => RecordedAction::Speed { scale },
                    (a, ..) => return Err(format!("robot_recorded action `{a}`: give play | pause | start alone, seek with t (s), step with delta (+1 | -1) or speed with scale (one of {})", SPEED_SCALES.map(|s| s.to_string()).join(", "))),
                };
                RobotAction::Recorded { action }
            }
        })
    }
}
