//! Robot mode's REST commands: the registry's spec table and the
//! conversion of a REST command ([`wire::Command`]) into [`RobotAction`].
use super::*;
use crate::app::actions::{Spec, spec};
use crate::robot::motion::KEYS;

impl actions::Action for RobotAction {
    fn commands() -> Vec<Spec> {
        fn c(name: &'static str, example: Value, description: &str) -> Spec {
            spec(name, actions::ROBOT, example, description)
        }
        vec![
            c("robot_guide", json!({}), "Start here: how robot mode works (concepts, workflows in order, every command with an example, rules) for an agent starting cold; topic narrows it (about, how_to_call, concepts, workflows, commands, rules). Also GET /v1/robot_guide."),
            c("robot_state", json!({}), "Read-only robot mode: file, workspace (the resolved root: root, found_by override | env | opened_file | cwd, from, error, rule; also in GET /v1/capabilities), status (loading | loaded | error, with the error naming the path), link_count, links, the selected link (mass, com, inertia, material and its density or material_in_file=false, file_notes), joints, motors, transmissions, battery, actuator_profiles (with content hashes), uncertainty, identification, the source block verbatim (the export's own `source`), source_file (--robot FILE's path, sha256, loaded_at, reload_count, watching, last_reload, run_reset; see robot_reload; watching=false for a preset), notice (the last reload's result), and cad_link (current | stale | missing | no_recorded_hash | no_source_file | unreadable, with the resolution rule and paths tried), and cad_threads (the CAD source's comment threads read in process from its .rcad, as robot_threads describes: open, source, line, read_at_revision, threads with their link and warning). Numbers are full-precision JSON; provenance is null unless the file carries a typed label (provenance_rule). format {version, name, …} names the loaded generation: physical v<N> (PhysicalModel; N is the file's version, 3 or later), or for a planar v2 file `planar v2 summary` with fidelity (robot_planar::FIDELITY, verbatim) and the planar build's warnings; a planar file also reports planar {unit, plane, source, bodies, joints (simulated or not), selected_body, selected_joint, frame (time, joint angles and targets, body poses, chain tips), frame_axes, jog_rule}, run from its own run thread, and unavailable (every refused action with its reason), with the v3-only blocks null. Also readouts (the Run section's live numbers: execution, performance with rtf, contacts, travel and walking speed, learning progress, motion progress, world load, neural residuals, joint readings, task observations, actuation profile and scheduled pushes, each null with the reason when the run publishes none), inputs (robot_inputs), view (robot_view), history (robot_history), leaderboard (robot_leaderboard), video (robot_video), the inspector section (run | link | joints | drives | source | comments) and scroll, run (null until loaded; phase idle with null time before any build; see robot_run), and overlays (--robot FILE run-thread contacts, joint frames and deflections with flags, counts, samples and scales, and overlays.stress for the read-only .simresult.json; available=false with the reason for presets; see robot_overlay). Nothing is written."),
            c("system_ui", json!({"action":{"operation":"controls"}}), "Discover the link list, inspector sections (section:link | joints | drives | source | comments), inspector scrolling and view controls, the run controls (run:start | pause | step | reset, and run:speed_down | run:speed_up | run:speed:<scale>: the same RobotAction::Speed as robot_speed), robot:reload and overlay:contacts | overlay:joints | overlay:deflections | overlay:stress for --robot FILE (the same RobotAction::Reload as robot_reload and RobotAction::Overlay as robot_overlay; overlay controls are listed for presets but disabled with the reason), for a controlled --robot FILE (a controller binding with a drive profile) the drive controls (drive:forward | drive:back | drive:left | drive:right | drive:stop | drive:action:<name>) and recording:save, replay:<file>, replay:cancel, replay:refresh (no jog:* there: its controller writes the servo targets), and for a preset the run, motion, recording, replay and gait preview controls (gait:open:<report>, gait:play, gait:pause, gait:stop, gait:seek:0 | - | + (±period/12 from the latest pose), gait:speed:0.25 | 0.5 | 1, gait:list: the same RobotAction::Gait as REST robot_gait), and for a recorded preset the timeline controls recorded:start | recorded:step- | recorded:play | recorded:pause | recorded:step+ | recorded:speed:<scale> (the same RobotAction::Recorded as REST robot_recorded) (controls) and activate one by id with the current ui_revision (activate), through the same handler as a click. Selection is shared by the list, the 3D view and robot_state."),
            c("robot_jog", json!({"joint":"left axle","target":0.5}), &format!("Servo-target jog of one joint by its file name: {JOG_LABEL}. Give target (absolute; rad, or m on a prismatic joint) or delta (from the current requested target). The same handler as the jog +/− buttons and system_ui jog:<joint>:+/- controls (±{JOG_STEP_RAD} rad, ±{JOG_STEP_M} m prismatic; listed for the joints touching the selected link). Errors name the joint: unknown joint, no servo target (passive joint, firmware none, fixed, or a trajectory-mode file), non-finite target, or a target outside the file's limits (with the limit; never clamped); after a failed run, Reset first. {JOG_SEMANTICS} robot_state.jog reports control mode, label and, per joint, the limit (or no limit in file), requested target, and the target and measured value from the latest accepted frame. For a planar v2 file: {}", planar::JOG_RULE)),
            c("robot_run", json!({"action":"start"}), "Run controls, the same handler as the Run/Pause/Step/Reset buttons and system_ui run:* controls. start runs the shared PhysicalRobot on the run thread (built from the loaded model with sim_runtime::registry() and BuildOptions::default()), paced at most to speed_scale × real time (robot_speed; default ×1); pause stops it; step advances exactly one 0.02 s chunk and is refused while running; reset rebuilds at t = 0 (assembly pose), bumps the generation and leaves it paused (allowed after a failure). A planar v2 file runs on its own thread (robot-run (planar v2)) through sim-phenomena's shared planar build (cad_robot::build_planar), built at open and paused at t = 0; start/pause/step/reset act on it the same way (reset rebuilds from the loaded model; Reload re-reads the file), and an advance error stops it with the error verbatim (robot_planar::PACING for its pacing; keys Space and R as well). An unknown action is an error naming it and listing the valid ones. robot_state.run reports phase (idle | building | running | paused | failed), time, steps (chunks), chunk_s, measured rtf, speed_scale (requested) and compute_limited, generation, error and the latest accepted frame. Nothing is written."),
            c("robot_speed", json!({"scale":4}), &format!("Set the run speed scale (× real time) for --robot FILE runs, preset runs and replays alike: scale one of {} (powers of two; anything else is refused naming the allowed values, never clamped), or action up | down alone (refused at ×8 / ×0.125, naming the limit). The same RobotAction::Speed as keys =/+ and − (numpad too), the header −/×scale/+ buttons (×scale resets to ×1) and system_ui run:speed_up | run:speed_down | run:speed:<scale>. Allowed in every phase; it applies from the next chunk (or the next Run) and survives Reset and a file reload. Pacing only: dt, chunk_s and the physics step are unchanged. {} robot_state.run reports speed_scale (requested), rtf (achieved) and compute_limited: {}. A planar v2 file takes the same scales for its own pacing: {}", SPEED_SCALES.map(|s| s.to_string()).join(", "), run::PACING, run::COMPUTE_LIMITED_RULE, planar::PACING)),
            c("robot_recorded", json!({"action":"seek","t":0.8}), &format!("Recorded-preset timeline ({}): action play | pause | start alone, seek with t (recorded time, s), step with delta (+1 | -1) or speed with scale. The same RobotAction::Recorded as the inspector Recorded buttons (Start, Step −1, Play, Pause, Step +1) and system_ui recorded:start | recorded:step- | recorded:play | recorded:pause | recorded:step+ | recorded:speed:<scale>. One playback worker (not the UI thread) owns the pre-mapped frames, runs the clock and publishes generation-stamped frames; the lookup is {}. {} {} {} {} speed accepts exactly one of {} (the run speed scales, never clamped) and is the same scale as robot_speed and the header −/×/+ buttons, which drive this playback for a recorded preset. Refused naming the reason: a non-recorded view (an embedded preset or --robot FILE), a non-finite or out-of-range t, a step at either end or not ±1, play while playing, pause while not playing. The response returns at once; robot_state.recorded reports label, preset, scene/capture paths, frame_count, first/last_time_s, duration_s, time_s, frame_index, frame_time_s, speed, phase (playing | paused | ended), generation, frame_generation and pending (a command not yet applied by the worker), description, readiness and evidence verbatim from presets.json, meta (the capture's source fidelity/cad_sha256/file/cad_revision, completed, error, simulated_s, stepping_wall_s, step_s, completed_steps, requested_steps as read; absent ones null and listed in absent), recorded_rate, unmatched_capture_links and the rules. Nothing is simulated.", crate::robot::preset::RECORDED_LABEL, sim_runtime::embedded_capture::LOOKUP_RULE, playback::CLOCK_RULE, playback::SEEK_RULE, playback::STEP_RULE, playback::START_RULE, SPEED_SCALES.map(|s| s.to_string()).join(", "))),
            c("robot_presets", json!({}), &format!("List the robot presets declared in {} (its paths resolved against the workspace root, reported in workspace): id, label, mode, scene/config/task paths, inputs_exist and missing, under_ignored_runs, capture, runs_as (EmbeddedEnvironment with a task, else EmbeddedSession; recorded playback for mode `recorded`) and openable with the reason when not (the build itself is not attempted): {}. Mode `embedded` runs natively; mode `recorded` plays back its capture (no physics).", crate::robot::preset::PRESETS, crate::robot::preset::OPENABLE_RULE)),
            c("robot_preset", json!({"id":"robot-measured-400hz"}), "Open a declared embedded or recorded preset by id. A recorded preset (mode `recorded`, a scene and a capture, e.g. robot-lift-5mm) reads its scene and its *-execution.json capture on the loader thread with the shared sim_runtime::embedded_capture reader, maps every frame to the scene's links by name and shows frame 0; robot_state.preset reports frame_count, duration_s, the capture's metadata as written (absent fields null), unmatched_capture_links and load_seconds; no physics is built, and run, jog, motion, save recording, replay, gait preview and overlays are refused naming the preset. An embedded preset opens in this window (replacing the current robot and stopping its run thread). Unknown ids, other modes and missing inputs are refused naming the id. The scene, config and task are parsed exactly as declared on a worker thread; scene.robot is drawn and inspected through the same loader as --robot FILE. Run/Pause/Step/Reset (robot_run) then drive the shared EmbeddedEnvironment (task) or EmbeddedSession (no task) on the run thread with seed 0 (recorded), one action interval or clamp(report_every, 1, 40) nominal steps per chunk. robot_state.preset reports id, label, paths, readiness and evidence verbatim, seed, step_s, chunk and step counts; run.phase `ended` with run.end reports a reached horizon or a terminated/truncated episode. Servo-target jog is not offered for presets."),
            c("robot_open", json!({"path": "/abs/arm.simrobot.json"}), "Open a *.simrobot.json (a physical model exported from CAD) in this window in place of the current robot, as robot_preset does for a preset: the old run stops, the new file loads off the UI thread and is watched for changes (robot_reload). Refused, naming the reason, for a path that is not a *.simrobot.json or does not exist, and while a recording is being written or a replay runs. The project's Test step uses it when Robot mode is already showing another robot."),
            c("robot_input", json!({"channels":{"command.forward_speed":0.001}}), &format!("Motion request for a running robot preset: {}. Give channels (values by motion channel name; the other motion channels keep their requested values) or key (w | a | s | d latches that key's request until stop, another key or a channel request; stop sets every motion channel to 0). The same handler as physical W/A/S/D (press/release) and X (stop), the W/A/S/D/Stop buttons and system_ui motion:w|a|s|d|stop. Motion channels come from the session's policy_contract.step_reference.config, else the preset's presets.json motion_commands (as web/viewer/motion-commands.mjs); key vectors from motion_key_vectors, else the channel bounds. Refused naming the channel and its bounds: an unknown channel, a session input that is not a motion channel, a non-finite value, or a value or summed key vector outside the channel's bounds ({}). Also refused, naming the reason: --robot FILE, a preset with no motion config, no built session (Run or Step builds it), a failed or ended run, an exhausted heartbeat. A declared motion_heartbeat is {} robot_state.motion reports source, channels with bounds, requested and held values, active keys, heartbeat, last refusal and the label.", motion::LABEL, motion::CLAMP_RULE, motion::HEARTBEAT_RULE)),
            c("robot_inputs", json!({"values":{"position.target": 0.4}}), &format!("Set named session inputs of a preset's held action (the browser's input sliders): values by input name, as robot_state.inputs lists them (name, kind, bounds, initial, held; the heartbeat and the residual.* motor corrections marked). The same RobotAction::Inputs as the Inputs block's sliders, its Reset inputs and Clear motor corrections buttons, and system_ui inputs:reset | inputs:clear_residuals. {} Refused naming the reason: a --robot FILE, a recorded preset, no built session yet (opening builds it), a failed or ended run, a replay holding the run, an unknown input (listing the inputs), the heartbeat, or a value outside the input's bounds. Answers robot_state.", run::INPUTS_RULE)),
            c("robot_view", json!({"follow": true, "display_hz": 30}), &format!("The 3D view's tools (the browser's view-tools): fit_selected: true frames the selected link's drawn bounds (Fit frames the whole robot again); follow (true | false): {} display_hz (one of {:?}): {} The same RobotAction::View as the view-tool chips and system_ui view:fit_selected | view:follow | view:display:<hz>. robot_state.view reports follow, follow_link, follow_target, display_hz and the rules. Refused naming the reason: fit_selected with nothing selected, follow with no link to follow, a display_hz not offered.", view_tools::FOLLOW_RULE, view_tools::DISPLAY_RATES, view_tools::DISPLAY_RULE)),
            c("robot_leaderboard", json!({"op": "list"}), &format!("The controller leaderboard ({}, the browser's leaderboard dialog through the shared sim_runtime::controller_leaderboard rule): op list (the filtered entries with rank, eligible, metrics and gates; full entries), open | close (the dialog), search {{text}}, status {{status: all | validated | experimental}}, profile {{group}} (a comparison group key; absent: all profiles, no shared ranking), select {{id, on}} and compare (evidence cards side by side), inspect {{id}} (one evidence card), run {{id}} (Load and run: opens tested recipe tested-<id> in place of the current robot, applies its evaluated step-0 inputs and runs), replay {{id}} (Replay tested inputs: writes the evaluated input events as an environment recording under runs/robot-presets/tested-<id>/ and replays it through the shared prepare_replay), download {{id}} (writes the evaluation JSON under runs/leaderboard/). {} Recipe and evidence files are checked against their recorded sha256 on the loader thread before a run or replay. The same RobotAction::Leaderboard as the dialog's controls (the header Leaderboard button opens it).", sim_runtime::controller_leaderboard::CATALOG, sim_runtime::controller_leaderboard::ELIGIBLE_RULE)),
            c("robot_video", json!({"on": true}), &format!("Record video of the 3D view (the browser's Record video): on: true starts, on: false stops and writes the file, absent flips (the header Record video / Stop video & save button). {} robot_state.video reports recording, path, seconds, frames, finishing and the last outcome (the file written, or why not).", crate::robot::video::VIDEO_RULE)),
            c("robot_history", json!({"t": 2.5}), &format!("Review the run's frame history (the Timeline block's slider and Live button): t (s, within robot_state.history.span) shows the kept frame at or before it (links, readouts, the graph dock's cursor and each trace's at_cursor value); a running run is paused first. live: true returns to the live frame (system_ui history:live). {}", run::HISTORY_RULE)),
            c("robot_graphs", json!({"pick": "learning:reward"}), &format!("The graph dock's picked channels: pick (a key from robot_state.graphs.candidates) adds a trace to the Picked chart, remove takes one away (system_ui pick:<key>), visible toggles the dock (as key G). {} robot_state.graphs reports picks, max_picks, candidates and, while reviewing history, cursor.", graphs::PICK_RULE)),
            c("robot_drive", json!({"forward":0.5,"lateral":0,"yaw":0}), "Drive a robot that has a drive profile: a controller binding (<model stem>.controller.json beside the --robot FILE) naming a sim.drive/1 profile and its external controller program. Give exactly one of: axes forward, lateral, yaw (normalized -1..1: + ahead, + left, + turn left/CCW; absent ones are 0), scaled by the profile's max_speed per axis (kinematics::scale; a nonzero axis the profile does not support, a value outside -1..1 or a non-finite one is refused naming the axis); action (one of the profile's named actions: stop approaches zero under the profile's acceleration limit, halt zeroes at once; an unknown name is refused listing the profile's actions); or stop: true (zero twist, approached under the acceleration limit). Mixing them (axes with action, action with stop, …) is refused naming the fields given. The same RobotAction::Drive as the bound keys and gamepad (drive_bindings; Escape stops, and window focus loss stops what the keys or gamepad were driving; the device layer zeroes axes the profile does not support and lists them in robot_state.drive_input.ignored_axes, where REST refuses them) and system_ui drive:forward | drive:back | drive:left | drive:right (one full-axis request each) | drive:stop | drive:action:<name>. A nonzero request is accepted only while the run is Running (robot_run start); a zero request, stop: true and the profile's stop and halt actions are accepted in any phase the run can take a twist. The run thread limits each request under the profile's max_accel and applies its deadman on simulated time: a request older than deadman.timeout_s (robot_state.drive) is lost and the robot ramps to a stop (or stops at once, per the profile), so a REST client must repeat its request faster than the deadman timeout to keep moving. Refused naming the reason: a robot without a drive profile, a planar v2 file, a nonzero request while the run is not running, a run that cannot take a twist (failed, ended, replaying), and while live motor sync streams (except stop and actions); a refusal is kept in robot_state.drive.last_refusal and robot_state.drive_input.last_error. Answers robot_state; robot_state.drive reports the profile, limits with units, geometry with provenance, request and commanded twist, deadman state and the controller identity."),
            c("robot_save_recording", json!({"note":"after motion:w"}), &format!("Save the loaded run's recording: the same handler as the Save recording button and system_ui recording:save. For a preset the run thread snapshots the shared recording (EmbeddedEnvironment::episode_recording() for a preset with a task, EmbeddedSession::recording() without, as the browser's Download); for a --robot FILE with a controller binding it snapshots the drive Session's recording (Session::recording(): the scene with the controller identity, the seed and one twist + heartbeat action per seam period) under runs/robot-drive/<model stem>/ ({}); in any phase with a built session, running, paused, ended or failed; a writer thread writes it, so the response returns at once with recording.pending set and robot_state.recording.last_saved {{path, meta_path, kind, version, completed_steps, replayable, not_replayable_reason, failure, saved_utc, bytes}} (or recording.error) once written. Optional path (relative to the root or absolute) and note (kept in the sidecar). {} {} {} Refused, naming the reason: a --robot FILE without a controller binding (its PhysicalRobot run keeps no recording) or whose binding failed to load, a recorded preset, no built session (Run or Step first), a replay in progress, a save still being written, a path under examples/, cad/ or web/, a name not ending in .json or ending in .meta.json, and an existing file (reported in recording.error).", recording::DRIVE_LOCATION_RULE, recording::LOCATION_RULE, recording::FILE_RULE, recording::REPLAYABLE_RULE)),
            c("robot_gait", json!({"report":"6216-Bayesian-009-472d11d4"}), &format!("Kinematic gait preview on the loaded preset: {}. Open a gait with report (a name in robot_state.gait_preview.reports: {}) or path (a compiled.json, relative to the workspace root or absolute); then {{\"action\":\"play\"}}, pause, stop, list, {{\"action\":\"seek\",\"t\":0.5}} (gait time, s) or {{\"action\":\"speed\",\"scale\":0.5}} (0 < scale <= 1). One worker reads the gait with sim_runtime::gait_playback::compiled_with_governor (governor from detailed.spec.json, else spec-identity.json, else none) and Gait::from_compiled, samples it ({}) and poses the scene with the shared KinematicMirror at lift {} m (web/viewer/calibration-mirror.mjs). Refused naming the reason: --robot FILE (no scene), a missing file (named), an unknown report, a gait joint that is not a coordinate of the preset's scene (named), a mirror that cannot serve the scene, a running physics run or a replay in progress; Run, Step and Replay are refused while a gait is loaded. Load errors after the command returns land in robot_state.gait_preview.error, with any previous preview kept. robot_state.gait_preview reports label, phase (idle | loading | playing | paused | failed), generation and frame_generation, report, compiled, governor_source, period_s, nominal_speed_m_s, report_speed_m_s, status and fidelity (the report's, verbatim), gait_time_s, speed_scale, desired_rad and commanded_rad by joint, drives, lift_m, authored_limit_violations and solve_ms. Nothing is simulated, written or sent to hardware.", gait::LABEL, gait::LISTING_RULE, gait::SAMPLING_RULE, gait::LIFT_M)),
            c("robot_replay", json!({"file":"20260930T060822.729Z.json"}), &format!("Replay a saved recording of the loaded preset, or of a --robot FILE with a controller binding (a drive session: {}): the same handler as the inspector Replay buttons and system_ui replay:<file>. Give file (a bare name listed in robot_state.recordings.files, in runs/robot-presets/<preset-id>/ or runs/robot-drive/<model stem>/) or path (any readable recording .json, relative to the root or absolute; reading is not restricted). {{\"action\":\"cancel\"}} stops the replay between chunks (system_ui replay:cancel); {{\"action\":\"list\"}} lists the recordings again off the UI thread (system_ui replay:refresh). {} {} {} {} robot_state.replay reports path, phase (idle | replaying | cancelled | done | failed), completed/total with unit, completed_steps and recorded_completed_steps, verdict, error, measured, replaced and sidecar. Refused, naming the reason: a --robot FILE without a controller binding or whose binding failed to load, a replay already in progress, a running run (Pause first), a building session, a missing or non-.json file, a recording of the other kind, a runtime mismatch (the runtime's message), a session identity mismatch (the viewer's labelled check) and, for a drive session, any difference from the loaded binding's controller identity ({}).", recording::DRIVE_REPLAY_RULE, recording::REPLAY_RULE, recording::VERDICT_RULE, recording::IDENTITY_RULE, recording::MEASURED_RULE, recording::DRIVE_IDENTITY_RULE)),
            c("robot_reload", json!({}), &format!("Re-read the opened --robot FILE now: the same RobotAction::Reload as the watch, the header Reload button and system_ui robot:reload. {} Returns at once; the result lands in robot_state.source_file {{path, sha256 (of the displayed model's bytes), loaded_at (UTC), reload_count (successful reloads), unchanged_checks, watching, in_flight, last_reload {{trigger watch | manual, outcome loaded | unchanged | failed, error naming the path, at (UTC)}}, run_reset, showing_last_good, failing_error}} and robot_state.notice. A loaded reload replaces the model, meshes, link list, notes and cad_link, keeps the selected link by name (else clears it with a note), discards any run or jog and spawns a fresh idle run thread whose generation is the old one + 1 (robot_state.run.generation; graphs clear by the generation rule); a planar v2 file whose run was running starts again from t = 0 once rebuilt. Refused naming the reason: a preset, a load or reload already in flight. (robot_state.source is still the file's own export source block.)", source::RULE)),
            c("robot_overlay", json!({"contacts":true,"joints":true,"deflections":false,"stress":true}), &format!("Show or hide the --robot FILE overlays. stress (key H, system_ui overlay:stress; default off) colours the link meshes per vertex from the model's read-only .simresult.json through sim_domain_robot::stress_results ({}); robot_state.overlays.stress reports enabled, painting, path, mtime_unix_s and mtime_utc, status (current | stale | no recorded hash | no results file | invalid results file), recorded_physical_hash, model_physical_hash, peak_stress_pa per link, hotspot_links, error, absent and paint_seconds. {} Run-thread overlays: contacts (spheres at PhysicalRobot::contacts points with force lines at {} m/N; red on the ground, orange against another link), joints (PhysicalRobot::joint_frames: a white sphere and each axis drawn ±{} m in yellow, cyan, magenta) and deflections (PhysicalRobot::deflections: flexible-link boundary displacement lines magnified ×{}). Give any subset; the others keep their values. The same RobotAction::Overlay as keys C / J / F / H, the inspector overlay buttons and system_ui overlay:contacts | overlay:joints | overlay:deflections | overlay:stress. Run-thread defaults: all on. A planar v2 file draws only contacts (its chain-tip contact points, red dots); turning joints, deflections or stress on is refused naming why (they need a v3 export). {} Drawn in the model frame through RobotRoot's transform (the link meshes' parent), only from the latest accepted frame of the current generation. robot_state.overlays reports flags, frame_flags, frame_generation, frame_time, contacts {{count, sample: first {} of link, other (link name | ground), point, force, penetration}}, joints {{count, sample}}, deflections {{count, max_displacement_m}} and scales. Refused for presets (their session frames publish no contacts, joint frames or deflections, and a preset has no results file).", sim_domain_robot::stress_results::SCALE, stress::RULE, run::FORCE_SCALE_M_PER_N, run::JOINT_AXIS_HALF_M, run::DEFLECTION_MAGNIFICATION, run::OVERLAY_COST_RULE, run::OVERLAY_SAMPLE)),
            c("robot_threads", json!({"op": "reply", "thread": "a1", "body": "Checked on the bench: the bracket holds"}), "Robot mode: the comment threads of the export's CAD source, read and written in process from its .rcad (cad_link's resolved path; no RoboCAD service, no HTTP). robot_state.cad_threads: open, source, line, read_at_revision, reading, filter, current, draft, in_flight, undo, and each thread's id, number, node_id, node_name, link {index, name} or null, warning, resolved and messages. The threads are listed exactly as CAD mode lists them (sim_cad::annotations over the file's pinned stamps); while the section is shown (or a REST call waits) the file is checked every 2 s and read again when its size or modification time moved. A thread's part is on the link whose CAD body id or members name it, else its nearest ancestor's (the manifest's node parents; no name matching); a thread on no link, an evidence thread, and every thread of an export whose cad_link is not current carry a warning. op: state (default; waits for the read at the current epoch) | refresh (reads again) | open (thread: shows it and selects its link) | reply (thread? default the shown one, body, author? default \"You\") | edit (comment, body, thread?) | delete (comment, thread?; a thread's last message is refused) | resolve (thread?, resolved? absent toggles) | open_in_cad (thread? default the shown one: switches to CAD mode on the CAD file and opens the Comments dock on the thread once read). Each change is the same request CAD mode applies (cad::threads::Request, a person's comment), one at a time, on a job that reopens the file, refuses when its bytes are not the ones the threads were read from (changed on disk since: nothing written, read again), applies it (archive revision + 1) and saves atomically; a REST change waits for the write. Not undoable here (the file is saved at once; CAD mode's undo covers later edits there). New threads are placed in CAD mode (Annotate model). open_in_cad is refused while a draft is open. cad_threads is CAD mode's own command, refused outside CAD mode, and annotations is Inspect's."),
            c("state", json!({}), "Robot mode: {robot_state (as robot_state), viewer_mode}"),
            c("camera", json!({"focus":[0,0,0],"radius":0.5,"yaw":0.7,"pitch":0.4}), "Absolute orbit in the display frame (Y up); SI metres and radians: focus, radius > 0, yaw, pitch within ±1.5. Sets the shared orbit camera (as camera_set without its options): stops a glide or spin, drops a pending fit and returns to the turntable. camera_state reports it"),
            c("fit", json!({}), "Fit the robot: its bounds at 3.2 × their half diagonal, centred, from the current heading (a planar v2 file: the front view of its working plane once built)"),
        ]
    }
    fn controls() -> &'static [&'static str] {
        &[
            "link:<index>", "clear_selection", "view:fit_selected", "view:follow", "view:display:<hz>", "history:live", "pick:<key>", "section:<section>", "inspector:scroll_down", "inspector:scroll_up", "fit", "robot:reload", "graphs:toggle", "overlay:<kind>",
            "run:<action>", "run:speed_down", "run:speed_up", "run:speed:<scale>", "recorded:<transport>", "recorded:speed:<scale>", "jog:<joint>:-", "jog:<joint>:+",
            // A planar (v2) file: the arrow keys' joint (jog ids there are by built joint index).
            "joint:<index>",
            "motion:w", "motion:a", "motion:s", "motion:d", "motion:stop",
            "inputs:reset", "inputs:clear_residuals",
            // A controlled robot (controller binding + sim.drive/1 profile): one request per activation.
            "drive:forward", "drive:back", "drive:left", "drive:right", "drive:stop", "drive:action:<name>",
            "recording:save", "replay:<file>", "replay:cancel", "replay:refresh",
            "gait:open:<report>", "gait:play", "gait:pause", "gait:stop", "gait:seek:<step>", "gait:speed:<scale>", "gait:list",
            // The Leg calibration panel's controls (hardware::panel::controls), passed on to its handler.
            "hardware:<name>",
        ]
    }
}

/// A REST command as its action (the checks that need no view, with the
/// errors they always gave).
impl TryFrom<wire::Command> for RobotAction {
    type Error = String;
    fn try_from(command: wire::Command) -> Result<Self, String> {
        use wire::Command as W;
        Ok(match command {
            W::State => RobotAction::State,
            W::RobotState => RobotAction::RobotState,
            W::RobotThreads { op, thread, comment, body, author, resolved } => RobotAction::Threads { act: crate::robot::threads::from_rest(op.as_deref(), thread, comment, body, author, resolved)? },
            W::SystemUi { action: wire::Ui::Controls } => RobotAction::Controls,
            W::SystemUi { action: wire::Ui::Activate { id, ui_revision } } => RobotAction::Activate { id, ui_revision },
            W::Camera { focus, radius, yaw, pitch } => RobotAction::Camera { focus, radius, yaw, pitch },
            W::Fit => RobotAction::Fit,
            W::RobotRun { action } => RobotAction::Run { action: RunAction::parse(&action)? },
            W::RobotJog { joint, target, delta } => match (target, delta) {
                (Some(target), None) => RobotAction::JogTo { joint, target },
                (None, Some(delta)) => RobotAction::Jog { joint, delta },
                _ => return Err("robot_jog needs exactly one of target (absolute, rad or m) or delta".into()),
            },
            W::RobotPresets => RobotAction::Presets,
            W::RobotGuide { topic } => RobotAction::Guide { topic },
            W::RobotVideo { on } => RobotAction::Video { on },
            W::RobotLeaderboard { op, id, text, status, group, on } => {
                use crate::robot::leaderboard::BoardOp as B;
                let need = |id: Option<String>| id.ok_or_else(|| format!("robot_leaderboard {op} needs id (an entry id from robot_leaderboard {{op: list}})"));
                let board = match op.as_str() {
                    "list" => B::List,
                    "open" => B::Open,
                    "close" => B::Close,
                    "search" => B::Search { text: text.unwrap_or_default() },
                    "status" => B::Status { status: status.ok_or("robot_leaderboard status needs status: all | validated | experimental")? },
                    "profile" => B::Profile { group },
                    "select" => B::Select { id: need(id.clone())?, on: on.unwrap_or(true) },
                    "compare" => B::Compare,
                    "inspect" => B::Inspect { id: need(id)? },
                    "run" => B::Run { id: need(id)? },
                    "replay" => B::Replay { id: need(id)? },
                    "download" => B::Download { id: need(id)? },
                    other => return Err(format!("robot_leaderboard op `{other}` is not one of list, open, close, search, status, profile, select, compare, inspect, run, replay, download")),
                };
                RobotAction::Leaderboard { op: board }
            }
            W::RobotHistory { t, live } => match (t, live) {
                (Some(t), None) => RobotAction::History { t: Some(t) },
                (None, Some(true)) => RobotAction::History { t: None },
                _ => return Err("robot_history needs exactly one of t (a time in robot_state.history.span, s) or live: true".into()),
            },
            W::RobotGraphs { pick, remove, visible } => match (pick, remove, visible) {
                (Some(c), None, None) => RobotAction::Pick { channel: c, on: true },
                (None, Some(c), None) => RobotAction::Pick { channel: c, on: false },
                (None, None, Some(_)) => RobotAction::ToggleGraphs,
                _ => return Err("robot_graphs needs exactly one of pick (a channel key from robot_state.graphs.candidates), remove (a picked key) or visible (toggles the dock)".into()),
            },
            W::RobotView { fit_selected, follow, display_hz } => {
                if fit_selected.is_none() && follow.is_none() && display_hz.is_none() {
                    return Err("robot_view needs fit_selected: true, follow (true | false) or display_hz".into());
                }
                RobotAction::View { fit_selected: fit_selected.unwrap_or(false), follow, display_hz }
            }
            W::RobotInputs { values } => RobotAction::Inputs { values },
            W::RobotPreset { id } => RobotAction::OpenPreset { id },
            W::RobotOpen { path } => RobotAction::Open { path },
            W::RobotInput { channels, key } => {
                let request = match (channels, key.as_deref()) {
                    (Some(map), None) => MotionRequest::Channels(map),
                    (None, Some("stop")) => MotionRequest::Stop,
                    (None, Some(k)) => match k.chars().collect::<Vec<_>>()[..] {
                        [c] if KEYS.contains(&c) => MotionRequest::Key(c),
                        _ => return Err(format!("robot_input key `{k}` is not one of w, a, s, d, stop")),
                    },
                    _ => return Err("robot_input needs exactly one of channels ({\"<motion channel>\": value, …}) or key (w | a | s | d | stop)".into()),
                };
                RobotAction::Motion { request }
            }
            W::RobotDrive { forward, lateral, yaw, action, stop } => RobotAction::Drive { request: DriveRequest::from_fields(forward, lateral, yaw, action, stop, "robot_drive")? },
            W::RobotSaveRecording { path, note } => RobotAction::SaveRecording { path, note },
            W::RobotReplay { file, path, action } => match (action.as_deref(), file.is_some() || path.is_some()) {
                (None | Some("start"), _) => RobotAction::Replay { file, path },
                (Some("cancel"), false) => RobotAction::CancelReplay,
                (Some("list"), false) => RobotAction::RefreshRecordings,
                (Some(a @ ("cancel" | "list")), true) => return Err(format!("robot_replay action `{a}` takes no file or path")),
                (Some(a), _) => return Err(format!("unknown robot_replay action `{a}`; valid actions: start (default, with file or path), cancel, list")),
            },
            W::RobotGait { action, report, path, t, scale } => {
                let action = match (action.as_deref(), report, path, t, scale) {
                    (None | Some("open"), Some(r), None, None, None) => GaitAction::Open { source: GaitSource::Report(r) },
                    (None | Some("open"), None, Some(p), None, None) => GaitAction::Open { source: GaitSource::Path(p) },
                    (Some("seek"), None, None, Some(t), None) => GaitAction::Seek { t },
                    (Some("speed"), None, None, None, Some(scale)) => GaitAction::Speed { scale },
                    (Some("play"), None, None, None, None) => GaitAction::Play,
                    (Some("pause"), None, None, None, None) => GaitAction::Pause,
                    (Some("stop"), None, None, None, None) => GaitAction::Stop,
                    (Some("list"), None, None, None, None) => GaitAction::List,
                    (a, ..) => return Err(format!("robot_gait {}: give exactly one of report or path (open, the default), or action seek with t, speed with scale, or play | pause | stop | list alone", a.map_or("open".into(), |a| format!("action `{a}`")))),
                };
                RobotAction::Gait { action }
            }
            W::RobotReload => RobotAction::Reload { trigger: ReloadTrigger::Manual },
            W::RobotOverlay { contacts: None, joints: None, deflections: None, stress: None } => return Err("robot_overlay needs at least one of contacts, joints, deflections, stress (true | false)".into()),
            W::RobotOverlay { contacts, joints, deflections, stress } => RobotAction::Overlay { contacts, joints, deflections, stress },
            W::RobotSpeed { action, scale } => {
                let speed = match (action.as_deref(), scale) {
                    (None | Some("set"), Some(scale)) => SpeedRequest::Set { scale },
                    (Some("up"), None) => SpeedRequest::Up,
                    (Some("down"), None) => SpeedRequest::Down,
                    (a, _) => return Err(format!("robot_speed {}: give scale (one of {}) or action up | down alone", a.map_or("without scale".into(), |a| format!("action `{a}`")), SPEED_SCALES.map(|s| s.to_string()).join(", "))),
                };
                RobotAction::Speed { speed }
            }
            W::RobotRecorded { action: name, t, scale, delta } => {
                let action = match (name.as_str(), t, scale, delta) {
                    ("play", None, None, None) => RecordedAction::Play,
                    ("pause", None, None, None) => RecordedAction::Pause,
                    ("start", None, None, None) => RecordedAction::Start,
                    ("seek", Some(t), None, None) => RecordedAction::Seek { t },
                    ("step", None, None, Some(delta)) => RecordedAction::Step { delta },
                    ("speed", None, Some(scale), None) => RecordedAction::Speed { scale },
                    (a, ..) => return Err(format!("robot_recorded action `{a}`: give play | pause | start alone, seek with t (s), step with delta (+1 | -1) or speed with scale (one of {})", SPEED_SCALES.map(|s| s.to_string()).join(", "))),
                };
                RobotAction::Recorded { action }
            }
        })
    }
}
