//! `CadAction`'s REST commands and `system_ui` control patterns (the
//! capability list, `GET /v1/capabilities`), split from `actions` to keep
//! it under 700 lines. The catalogue commands' examples and id list are
//! generated from `ops::CATALOGUE`.
use super::actions::{CAD, CadAction};
use crate::app::actions::{self, Spec, spec};
use serde_json::{Map, Value, json};

impl actions::Action for CadAction {
    fn commands() -> Vec<Spec> {
        let mut specs = Self::core_commands();
        // cad-views-export: the display state and section, saved views, files, export and render.
        specs.extend(super::display::specs());
        specs.extend(super::views::specs());
        specs.extend(super::files::specs());
        // cad-physical-inspect: the Robot panel and robot tools, materials, the inspector's physical rows, results.
        specs.extend(super::robot::specs());
        specs.extend(super::materials::specs());
        specs.extend(super::inspector::physical_specs());
        specs.extend(super::results::specs());
        specs.extend(super::print::specs());
        specs
    }
    fn controls() -> &'static [&'static str] {
        &[
            "cad:undo", "cad:redo", "cad:save", "cad:refresh", "cad:fit", "cad:physical", "cad:delete", "cad:node:<id>", "cad:visible:<id>", "cad:locked:<id>", "cad:disabled:<id>", "cad:material:<id>:<mat>", "cad:command:<id>",
            "cad:mode:<mode>", "cad:select_all", "cad:invert_selection", "cad:select_same_material", "cad:edges_to_faces", "cad:candidate:<n>", "cad:tool:<tool>", "cad:cancel",
            "cad:op:<id>", "cad:surface:<kind>", "cad:menu:<category>", "cad:form:ok", "cad:form:cancel", "cad:form:set:<name>:<value>",
            // cad-views-export (part D: display, section, views; part E: files).
            "cad:display:<setting>", "cad:section:<setting>", "cad:view:<id>", "cad:file:<op>",
            // cad-physical-inspect.
            "cad:robot:<id>", "cad:robot:row:<id>", "cad:robot:button:<id>", "cad:materials:<id>", "cad:inspect:<id>", "cad:results:<id>",
            // cad-print.
            "cad:print:<id>",
        ]
    }
}

impl CadAction {
    /// The commands written before cad-views-export.
    fn core_commands() -> Vec<Spec> {
        vec![
            spec("state", CAD, json!({}), "CAD mode: the same answer as cad_state, plus viewer_mode."),
            spec("cad_state", CAD, json!({}), "CAD mode: the RoboCAD document as this window shows it: target (file or service URL), service (self-started or attached; url, pid), connection (connecting | connected | lost with the error verbatim), health (RoboCAD's GET /: path, dirty, gui, nodes, document_id, revision), stale (why the shown tree may be behind RoboCAD, or null), nodes (id, kind, name, parent, depth, visible, effective_visible, locked, disabled), selection (RoboCAD's items [node, kind, index], synced with its /selection), select_mode (body | face | edge | vertex | point), hover (the item under the pointer, display only), candidates (the Alt menu while open), selection_error (why the last read of RoboCAD's /selection failed, or null), unsaved (RoboCAD's dirty flag, or null when it can't be confirmed: not connected, or an edit in flight or just finished), inspected (RoboCAD's node detail for the first selected node, exactly as returned), physical (fetched with cad_physical), history (undo and redo labels), commands (RoboCAD's GUI registry; empty headless), autosave (GUI only), edit (the mutating request in flight, by name), meshes (shown, pending, failed), tool (the active tool), tool_state (pivot, drag and preview with the revision each began at, push/pull target, numeric fields with their evaluations, last measurement, snap, readout), ops (the catalogue operations: the open parameter form with each field's text and evaluation, the active pick or place operation, the primitive being placed, the open command surface, the cursor snap, the last copy, and the catalogue: id, label, category, keys, flow, route, parameters) and status (the last outcome)."),
            spec("cad_open", CAD, json!({"path": "examples/camera-turntable/cad/turntable.rcad"}), "CAD mode: open a .rcad file (path: RoboCAD's headless service is started on it with cad/.venv/bin/python -m robocad.api PATH --port N, and stopped when the document closes) or attach to a running RoboCAD (url, loopback only, e.g. http://127.0.0.1:8420; never stopped). Refused, naming the reason, while an edit is in flight or while a self-started document has unsaved edits or edits whose saved state can't be confirmed (not connected to it; save first: the viewer never saves for you). Answers once the service is starting; poll cad_state for the connection."),
            spec("cad_select", CAD, json!({"items": [["n1", "face", 2]], "extend": false}), "CAD mode: select items as RoboCAD writes them (items: [[node, kind, index], ...], kind body | face | edge | vertex | point; ids: node ids as body items [id, \"body\", 0]; [] clears; extend adds like Shift; toggle adds or removes like Ctrl). The same action as a click on a tree row, a pick or box select in the 3D view, or a choice in the Alt menu. Pushed to RoboCAD's PUT /selection with the selection mode, so RoboCAD's window shows it too; RoboCAD's own selection changes come back on the next poll."),
            spec("cad_select_mode", CAD, json!({"mode": "face"}), "CAD mode: the selection mode (body | face | edge | vertex | point; RoboCAD's B, Shift+B, E, V, P): what a click in the 3D view picks. Clears the selection, as RoboCAD does. A headless RoboCAD does not store the mode (its GET /selection has none), so the viewer holds it; a desktop RoboCAD's mode is adopted when it changes there."),
            spec("cad_hover", CAD, json!({"item": ["n1", "face", 2]}), "CAD mode: the hover highlight (item [node, kind, index], or null to clear). Display only: nothing is sent to RoboCAD."),
            spec("cad_box_select", CAD, json!({"rect": [300.0, 200.0, 600.0, 450.0]}), "CAD mode: box select over the window rectangle rect [x0, y0, x1, y1] (logical pixels), as RoboCAD's drag: in body mode the bodies whose bounding box lies inside, in edge mode the edges whose sampled polylines lie inside, in vertex mode the vertices inside. extend keeps the selection (Shift or Ctrl)."),
            spec("cad_candidates", CAD, json!({"items": [["n1", "face", 2], ["n2", "face", 0]]}), "CAD mode: open the Alt+click menu over stacked candidates (items as cad_select's; extend, toggle say how a choice applies). Its entries are system_ui controls cad:candidate:<n>."),
            spec("cad_select_all", CAD, json!({}), "CAD mode: RoboCAD's Select All (Ctrl+A): every visible body, sheet, curve, instance and mesh, as body items."),
            spec("cad_invert_selection", CAD, json!({}), "CAD mode: RoboCAD's Invert Selection (Ctrl+Shift+I): the visible bodies, sheets, curves, instances and meshes not selected now."),
            spec("cad_select_same_material", CAD, json!({}), "CAD mode: RoboCAD's Select Same Material (Ctrl+Shift+M): every node with the first selected node's material."),
            spec("cad_edges_to_faces", CAD, json!({}), "CAD mode: RoboCAD's 'Selection: edges → bounding faces': each selected edge becomes the faces it bounds (found from RoboCAD's tessellation: faces with a triangle side along the edge), and the mode becomes face."),
            spec("cad_tool", CAD, json!({"tool": "move"}), "CAD mode: activate a tool (select | move | rotate | scale | push_pull | offset_face | measure; RoboCAD's Escape, G, R, S, D, Shift+D, M). Move, rotate and scale place the gizmo at the first selected node's pivot (else the selection's centre); push/pull and offset target the first selected face; measure takes two picks. Display only until a commit."),
            spec("cad_transform", CAD, json!({"translation": [10.0, 0.0, 0.0]}), "CAD mode: commit a transform as exactly one POST /ops/transform (RoboCAD's Ops.transform: translation [dx, dy, dz] mm, or axis [x, y, z] with angle_deg about center, or a uniform scale factor about center) on the selected nodes or ids. revision: RoboCAD's revision the preview began at (refused, naming it, when the document changed since). Refused while another edit is in flight. RoboCAD's command layer applies it as one undo step."),
            spec("cad_push_pull", CAD, json!({"node": "n1", "face": 3, "distance": 5.0}), "CAD mode: push/pull planar face index face of node by distance mm along its normal: exactly one POST /ops/push_pull (one undo step in RoboCAD). revision as cad_transform's. Refused while another edit is in flight."),
            spec("cad_offset_faces", CAD, json!({"node": "n1", "faces": [3], "distance": 1.5}), "CAD mode: offset faces of node by distance mm: exactly one POST /ops/offset_faces (one undo step). revision as cad_transform's."),
            spec("cad_set_dimension", CAD, json!({"node": "n1", "dimension": "diameter", "faces": [4], "value": 8.0}), "CAD mode: set a live dimension of the selected faces (RoboCAD's live_dimensions): diameter of a cylindrical face (faces [f], set_diameter), distance between two parallel planar faces (faces [a, b], b moves, set_distance) or angle between two planar faces (faces [a, b], degrees, set_angle). Exactly one POST /ops call; revision as cad_transform's."),
            spec("cad_numeric", CAD, json!({"values": ["20mm + 0.3"]}), "CAD mode: the numeric bar's Enter: values are the active tool's fields as typed (move dx dy dz, rotate angle, scale factor, push/pull or offset distance, a live dimension), each a unit expression RoboCAD's numeric bar accepts (20mm + 0.3, 1in, pi*10, 45deg; bare numbers are mm or degrees), evaluated by sim_runtime::units. An error names the token and its position. Commits through the tool's one call."),
            spec("cad_measure", CAD, json!({"a": {"item": ["n1", "face", 0], "point": [0.0, 0.0, 0.0]}, "b": {"item": ["n1", "face", 5], "point": [0.0, 0.0, 20.0]}}), "CAD mode: measure between two picks as RoboCAD's measure tool (distance between parallel planar faces, the angle between faces or between line edges, an edge's radius when both picks are the same circular edge, else the points' distance). Answers the measurement; keep (RoboCAD's Shift+click) also adds it as a measure node with exactly one POST /ops/add_measurement."),
            spec("cad_cancel", CAD, json!({}), "CAD mode: Escape: cancel a preview and return to the Select tool; in the Select tool, clear the selection. Nothing is sent to RoboCAD except the cleared selection."),
            spec("cad_patch", CAD, json!({"id": "n1", "attrs": {"visible": false}}), "CAD mode: PATCH /nodes/{id} with attrs exactly as RoboCAD accepts them (name, visible, locked, disabled, material, color, pivot, transform, parent, index, tessellation_tolerance, plane, sketch): RoboCAD's command layer applies it as one undo step. One edit at a time: refused while another is in flight. Answers RoboCAD's node detail, or its error verbatim."),
            spec("cad_delete", CAD, json!({"id": "n1"}), "CAD mode: DELETE /nodes/{id} through RoboCAD's delete command (undoable there). Refused while another edit is in flight."),
            spec("cad_undo", CAD, json!({}), "CAD mode: POST /undo: RoboCAD undoes its last command; answers the label undone and the history."),
            spec("cad_redo", CAD, json!({}), "CAD mode: POST /redo: RoboCAD redoes; answers the label redone and the history."),
            spec("cad_save", CAD, json!({}), "CAD mode: POST /save/thumbnail: RoboCAD writes its document to its own path (or path, absolute with ~/ expanded and .rcad appended when missing, to save as) with the desktop's thumbnail, as RoboCAD's Save does; answers {saved, thumbnail}; a document this window started follows the saved file. The viewer never writes the .rcad itself."),
            spec("cad_command", CAD, json!({"id": "view.fit"}), "CAD mode: run a RoboCAD GUI registry command by id (POST /commands/{id}; ids from cad_state.commands). RoboCAD's desktop window only: a headless service answers 409 \"no GUI\", shown verbatim."),
            spec("cad_op", CAD, json!({"name": "rename", "args": ["n1", "Bracket"]}), "CAD mode: call RoboCAD's command layer (POST /ops/{name} {args, kwargs}; names and signatures from RoboCAD's GET /ops). Works headless. Refused while another edit is in flight."),
            spec("cad_invoke", CAD, json!({"id": "tool.fillet"}), format!("CAD mode: invoke a catalogue operation by RoboCAD's command id, as its menu entry, toolbar button, palette row, radial entry or key does: an immediate one runs at once on the selection with RoboCAD's defaults (one edit; refused by name, with nothing sent, when the selection does not fit, with RoboCAD's message); a form one (RoboCAD's dialog) checks the selection and opens its parameter form (cad_state.ops.form; then cad_form_set, cad_form_submit or cad_form_cancel); a pick one (fillet, chamfer, shell) switches the selection mode, keeps the selection and opens its form beside the view, staying active across runs; a place one (box, cylinder, sphere) starts placing on the active plane (else XY) with its form for exact sizes; a sketch tool (sketch.line … sketch.text) starts clicking points on the active plane (else XY) with its Tab values in its form, each finished shape one cad_sketch; extrude and revolve start their tool (a drag release extrudes by the dragged height with taper 0, a revolve press and release turns 360°, as RoboCAD's; the form's OK uses the typed distance, taper or angle); a plane tool (tool.plane, plane_three, plane_camera, plane_mid) starts picking faces or points, each complete set one plane op whose new plane becomes active; tool.plane_xy/xz/yz and tool.plane_2d_snap set viewer state only (the active plane, 2D snapping) and are never refused for an edit in flight. An id that is not in the catalogue is one of RoboCAD's other commands: its native action, or a refusal naming why (the epic that owns it, or why it is not ported). The catalogue: {}.", catalogue_list())),
            spec("cad_run", CAD, run_example(), "CAD mode: run catalogue operation id now with params (each a number, a unit expression as its field takes it (\"2 mm + 0.5\", \"45deg\"), a choice's option, true/false, or [x, y, z]; absent ones take RoboCAD's defaults; parameter names per id in cad_invoke's list and cad_state.ops.catalogue) on items (RoboCAD's [node, kind, index]; the selection when absent). revision: RoboCAD's revision the values and picks were made at (refused, naming it, when the document changed since); required when items name faces or edges, whose indices belong to one revision. A parameter whose when-condition does not hold (an Array row of the other kind) is refused by name. Refused by name, with nothing sent, while another edit is in flight, when not connected, when the shown tree is behind RoboCAD's, when a selected face or edge was picked at an older revision, or when the selection does not fit (RoboCAD's message). Where RoboCAD's handler loops over the selected nodes, one Ops call per node runs inside the one edit job, each its own RoboCAD undo step; the first error stops the rest and says how many ran. Read-only operations (copy, control points, curvature comb, continuity) answer when their read has started; their results show in cad_state."),
            spec("cad_form_set", CAD, json!({"name": "radius", "value": "2 mm"}), "CAD mode: set the open parameter form's field name to value (a field's text as typed, a choice's option, true/false for a checkbox, [x, y, z] for a point). Answers the form with each field's evaluation or the error naming the bad token. Refused when no form is open or it has no such field."),
            spec("cad_form_submit", CAD, json!({}), "CAD mode: the open form's OK: its fields evaluated, then the operation runs as cad_run with the form's opening revision (a pick or place tool's form uses its picks' own revision guard). A refusal or error keeps the form open and shows in it (cad_state.ops.form.error); a form operation's form closes once its edit has started, a pick or place tool's stays open and active."),
            spec("cad_sketch", CAD, json!({"node": "n1", "calls": [["trim", [0, [1], [5.0, 2.5]]]], "revision": 12}), "CAD mode: edit a sketch with RoboCAD's sketch calls, [method, [args...], {kwargs}?] as kernel/sketch.py names them (constructors line, polyline, spline, control_curve, circle, circle_two_point, circle_three_point, circle_tangent(curves, radius?, near?), ellipse, arc, arc_three_point, arc_tangent(prev, end), rectangle, rectangle_center, rectangle_three_point, polygon, slot, spiral, text; edits remove, reverse, split_at, trim, extend, fillet_corner, offset, join, unjoin, insert_vertex, remove_vertex, rebuild; points [u, v] mm in the sketch plane, curves by index). Each call is checked first (a refusal names the call and the argument, or a curve index past the sketch's curves; circle_tangent's curves and arc_tangent's prev are curve indices too). One POST /nodes/{node}/sketch (one RoboCAD undo step); without node, the sketch RoboCAD's sketch tools would draw into on plane (xy | xz | yz | a plane node id; the active plane when absent, else xy): the selected sketch on that plane, else the first visible one, else one new sketch on it carrying the calls (POST /nodes {kind: sketch}). The sketch tools' finished shapes are this command. revision: RoboCAD's revision the curve indices were read at (refused, naming it, when the document changed since). Refused by name while another edit is in flight."),
            spec("cad_form_cancel", CAD, json!({}), "CAD mode: the open form's Cancel (Escape): closes it and ends its pick, place, sketch, extrude or plane interaction (a sketch shape's clicked points, an extrude drag and a plane tool's picks are dropped). Nothing is sent to RoboCAD."),
            spec("cad_surface", CAD, json!({"surface": {"kind": "palette", "query": "fillet"}}), format!("CAD mode: open a command surface built from the catalogue and RoboCAD's command table: palette (query), menu (category, one of RoboCAD's menus: {}; the General, Window and Tools commands are in Help, as RoboCAD puts them), context (the right-click menu, at [x, y] window logical px, else the 3D view's centre), view_radial (Space) and select_radial (Q) (at as context's); closed closes it. Display only: its entries write the same cad_invoke and CAD actions a click does.", super::surfaces::registry::CATEGORIES.join(", "))),
            spec("cad_refresh", CAD, json!({}), "CAD mode: refetch RoboCAD's /doc, /commands and /autosave now."),
            spec("cad_fit", CAD, json!({}), "CAD mode: frame the native 3D view on every shown body, or on node id. Display only: RoboCAD's own view and the geometry are not changed."),
            spec("cad_physical", CAD, json!({}), "CAD mode: fetch RoboCAD's physical description (GET /physical?flex=0; nothing is written) for the inspector: the link holding the selected body, its mass, centre of mass and inertia, and mass_sources as RoboCAD labels them (declared measurement source, material density, ...), never filled in."),
            spec("system_ui", CAD, json!({"action": {"operation": "controls"}}), "CAD mode: its controls (cad:undo, cad:redo, cad:save, cad:refresh, cad:fit, cad:physical, cad:delete, cad:node:<id> to select a tree row, cad:visible:<id> to toggle visibility, cad:locked:<id> to toggle locked, cad:disabled:<id> to toggle disabled, cad:material:<id>:<mat> to assign material <mat> (an id from RoboCAD's /doc materials) to node <id>, cad:command:<id> for RoboCAD's registry commands, cad:mode:<mode> for a selection mode, cad:select_all, cad:invert_selection, cad:select_same_material, cad:edges_to_faces, cad:candidate:<n> for an entry of the open Alt menu, cad:tool:<tool> to activate a tool, cad:cancel for Escape, cad:op:<id> to invoke a catalogue operation as cad_invoke, cad:surface:<kind> to open a command surface (palette, context, view_radial, select_radial, closed), cad:menu:<category> for a category's menu, cad:form:ok and cad:form:cancel for the open form's buttons, cad:form:set:<name>:<value> to set one of its fields, cad:display:<setting> for the display state as cad_display (mode_shaded, mode_shaded_edges, mode_wireframe, mode_xray, mode_matcap, mode_render, next for the next mode, and grid, build_plate, high_contrast, view_cube, comment_pins to toggle one), cad:section:<setting> for the section tool as cad_section (toggle, x, y, z for a plane across that axis through the drawn bodies' centre, rotate for 90° about Z, exact for the selected node's exact section), cad:view:<id> for saved views as cad_views (panel to show or hide the Saved Views panel, list, save with the panel's typed name, <id> to restore a view, replace-<id> to replace it with the current camera and display, delete-<id>), cad:file:<op> for files as cad_file, cad_export and cad_render (new, open, save_as, import, export, export_drawing, render, and close while a path form is open)), each with enabled and disabled_reason, then the mode switcher's mode:* controls; activate {id} writes the same CAD action a click does."),
        ]
    }
}

/// `cad_run`'s example, from the catalogue: tool.fillet with its first parameter's default.
fn run_example() -> Value {
    let mut params = Map::new();
    if let Some(p) = super::ops::entry("tool.fillet").and_then(|e| e.params.first()) {
        params.insert(p.name.to_string(), Value::String(p.default.to_string()));
    }
    json!({"id": "tool.fillet", "params": params})
}

/// Every catalogue id with its label and parameters (name=default; "name?" for an empty default).
fn catalogue_list() -> String {
    super::ops::CATALOGUE
        .iter()
        .map(|e| {
            let params: Vec<String> = e.params.iter().map(|p| if p.default.is_empty() { format!("{}?", p.name) } else { format!("{}={}", p.name, p.default) }).collect();
            if params.is_empty() { format!("{} ({})", e.id, e.label) } else { format!("{} ({}: {})", e.id, e.label, params.join(", ")) }
        })
        .collect::<Vec<_>>()
        .join("; ")
}
