import fs from 'node:fs';
import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
import crypto from 'node:crypto';
const d='examples/full-robot/contact-planning/';
const read=n=>JSON.parse(fs.readFileSync(d+n));
const same=(a,b,label)=>assert(isDeepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b))),label);
const refined=read('joint-body16-refinement.result.json'),g=read('joint-body16-grouped-one-step.result.json'),o=read('joint-body16-ordinary-one-step.result.json');
same(refined.original_report,read('joint-timed-speed.result.json').report,'Original CAD report changed before refinement');
same(g.initial_report,refined.refined_report,'Refined initial report changed');
for(const field of ['candidate','report','initial_report','returned_candidate_error','search','best_sampled_feasible','jacobian_nonzeros','dense_jacobian_entries','constraint_projection']) same(g[field],o[field],`Grouped 16-control pilot changed ${field}`);
assert.equal(g.model_evaluations,220);assert.equal(o.model_evaluations,508);
assert.equal(g.grouped_body_probes,96);assert.equal(g.body_group_fallbacks,0);
assert.equal(g.initial_report.constraints.inequalities.length,7192);
assert.equal(refined.refined_variables,491);
same(g.search.final_evaluation.constraints,g.report.constraints.inequalities,'Native final constraints differ from independent full audit');
assert.equal(g.search.final_evaluation.objective,.5*g.report.constraints.objective[0]**2);
assert(fs.readFileSync('runs/joint-body16/legacy.recipe.json').equals(fs.readFileSync(d+'joint-body8-speed.recipe.json')));
assert(fs.readFileSync('runs/joint-body16/legacy-initial.result.json').equals(fs.readFileSync(d+'joint-body8-speed-initial.result.json')));
const identity=n=>{const path=d+n,bytes=fs.readFileSync(path);return {path,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};};
const summarize=r=>({speed_m_s:r.motion_report.speed_m_s,force_error_n:r.motion_report.maximum_force_error_n,moment_error_nm:r.motion_report.maximum_moment_error_nm,torque_margin_nm:r.motion_report.minimum_torque_margin_nm,maximum_inequality:Math.max(...r.constraints.inequalities),sampled_feasible:r.sampled_feasible});
const result={controls:16,variables:491,frames:266,constraints:7192,old_preparer_recipe_and_initial_byte_identical:true,initial_full_report_matches_refinement:true,grouped_native_search_and_full_cad_identical_to_ordinary:true,grouped_model_evaluations:g.model_evaluations,ordinary_model_evaluations:o.model_evaluations,grouped_body_probes:g.grouped_body_probes,body_group_fallbacks:g.body_group_fallbacks,jacobian_nonzeros:g.jacobian_nonzeros,dense_jacobian_entries:g.dense_jacobian_entries,initial:summarize(g.initial_report),final:summarize(g.report),artifacts:['joint-body16-refinement.result.json','joint-body16-grouped-one-step.result.json','joint-body16-ordinary-one-step.result.json','check_joint_body16.mjs'].map(identity),scope:'Exact eight-to-sixteen body refinement, extra collocation frames retained and grouped/ordinary native pilot agreement. Same physical model and target; neither initial nor pilot is a qualified runtime gait or physical speed maximum.'};
fs.writeFileSync(d+'joint-body16-verification.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({...result,artifacts:undefined}));
