import fs from 'node:fs';
import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
const d='examples/full-robot/contact-planning/',read=n=>JSON.parse(fs.readFileSync(d+n));
const same=(a,b,label)=>assert(isDeepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b))),label);
const original=read('joint-conic-warm-final.result.json'),rechecked=read('joint-conic-warm-final-rechecked.result.json');
for(const k of ['candidate','report','independent_affine_error','force_box_violation_n'])same(original[k],rechecked[k],`Conic primal-iterate audit changed ${k}`);
const oldSearch={...original.search},newSearch={...rechecked.search};delete newSearch.has_primal_candidate;same(oldSearch,newSearch,'Conic primal-iterate audit changed native search');assert(rechecked.search.has_primal_candidate);
const pilot=read('joint-conic-feasible-pilot.result.json');same(pilot.initial_report,original.report,'Native pilot initial CAD report differs');assert(pilot.report.sampled_feasible);assert(pilot.report.motion_report.speed_m_s>pilot.initial_report.motion_report.speed_m_s);same(pilot.search.final_evaluation.constraints,pilot.report.constraints.inequalities,'Pilot native rows differ from final CAD audit');assert.equal(pilot.model_evaluations,244);
const dense=read('joint-conic-feasible-dense.result.json');assert.equal(dense.motion_report.frames.length,2250);assert(!dense.sampled_feasible);
const key=f=>JSON.stringify([f.clock.phase_rate,f.clock.phase_acceleration_per_s,f.time_s]);const frames=new Map(dense.motion_report.frames.map(f=>[key(f),f]));
for(const f of original.report.motion_report.frames){const other=frames.get(key(f));assert(other,'Dense audit lost an old frame');const a={...f},b={...other};delete a.residual_weight;delete b.residual_weight;same(a,b,'Dense audit changed old physical frame');}
const first=read('joint-conic-dense-refit.result.json'),final=read('joint-conic-dense-audit.result.json');const finalSearch={...final.search};delete finalSearch.has_primal_candidate;same(first.search,finalSearch,'Auditing approximate conic iterate changed native result');assert.equal(final.search.status,'AlmostSolved');assert(!final.search.solved);assert(final.search.has_primal_candidate);assert(final.independent_affine_error<1e-8);assert(final.force_box_violation_n===0);assert(final.report.maximum_cone_violation_n===0);assert(!final.report.sampled_feasible);
const summary={original_mesh_native_pilot:{speed_m_s:pilot.report.motion_report.speed_m_s,model_evaluations:244,sampled_feasible:true,native_full_constraints_match:true},dense_audit:{frames:2250,old_physical_frames_preserved:250,force_error_n:dense.motion_report.maximum_force_error_n,moment_error_nm:dense.motion_report.maximum_moment_error_nm,sampled_feasible:false},dense_refit:{status:final.search.status,numerical_minimax_balance:final.search.values.at(-1),primal_dual_gap:final.search.primal_dual_objective_gap,force_error_n:final.report.motion_report.maximum_force_error_n,moment_error_nm:final.report.motion_report.maximum_moment_error_nm,friction_cone_violation_n:0,sampled_feasible:false},scope:'A usable sampled initializer and feasible one-step joint speed increase, rejected by dense validation. No measured runtime speed gain or physical speed maximum.'};
fs.writeFileSync(d+'joint-force-conic-followup-verification.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(summary));
