import fs from 'node:fs';
import assert from 'node:assert/strict';
import {isDeepStrictEqual as eq} from 'node:util';
import {gzipSync,gunzipSync} from 'node:zlib';
import crypto from 'node:crypto';
const d='examples/full-robot/contact-planning/';const path=d+'joint-body16-domain4000.result.json';
const raw=fs.existsSync(path)?fs.readFileSync(path):gunzipSync(fs.readFileSync(path+'.gz'));
const r=JSON.parse(raw),x=r.restoration.restoration,[candidate,report]=x.evaluation;
const target=JSON.parse(fs.readFileSync(d+'joint-body16-domain-audit.recipe.json'));
const expected=structuredClone(target);expected.candidate=candidate;
assert(eq(expected,r.restored_recipe),'Restoration changed fixed target fields');
assert.equal(r.restoration.reference_body_refinements,1);assert.equal(x.attempts.length,26);
assert(x.attempts[0].rejection===null&&x.attempts[1].rejection!==null);
assert(x.rejected_upper_fraction>x.fraction&&x.rejected_upper_fraction-x.fraction<=2**-24);
assert(x.attempts.some(a=>a.fraction===x.fraction&&a.rejection===null));
assert(x.attempts.some(a=>a.fraction===x.rejected_upper_fraction&&a.rejection!==null));
const audit=structuredClone(expected);audit.robot.uniform_samples=4000;
audit.robot.additional_phases=[...new Set([...target.robot.additional_phases,...Array.from({length:1000},(_,i)=>(i+.5)/1000)])].sort((a,b)=>a-b);
assert(eq(audit,r.audit_recipe),'Combined audit did not preserve old uniform phases');
assert.equal(report.motion_report.frames.length,10266);
assert(report.motion_report.frames.every(f=>f.maximum_inter_link_penetration_m===0&&f.maximum_floor_penetration_m<=target.robot.penetration_tolerance_m));
assert(report.sampled_feasible);assert(report.constraints.inequalities.every(x=>x<=0));
for(let i=0;i<x.values.length;i++)assert(x.values[i]>=target.variables[i].bound.lower&&x.values[i]<=target.variables[i].bound.upper);
const prior=JSON.parse(fs.readFileSync(d+'joint-body16-domain.summary.json'));
const failedPhases=[...new Set([...prior.attempts,...x.attempts].flatMap(a=>{const m=a.rejection?.match(/^contact phase ([^,]+),/);return m?[Number(m[1])]:[];}))].sort((a,b)=>a-b);
const coarse=JSON.parse(fs.readFileSync(d+'joint-body16-domain.recipe.json'));coarse.candidate=candidate;
coarse.robot.additional_phases=[...new Set([...coarse.robot.additional_phases,...failedPhases])].sort((a,b)=>a-b);
fs.writeFileSync(d+'joint-body16-domain4000-optimization.recipe.json',JSON.stringify(coarse,null,2)+'\n',{flag:'wx'});
const summary={accepted_fraction:x.fraction,rejected_upper_fraction:x.rejected_upper_fraction,attempts:x.attempts,frames:10266,failed_phases_added_to_optimization:failedPhases,speed_m_s:report.motion_report.speed_m_s,force_error_n:report.motion_report.maximum_force_error_n,moment_error_nm:report.motion_report.maximum_moment_error_nm,torque_margin_nm:report.motion_report.minimum_torque_margin_nm,maximum_cone_violation_n:report.maximum_cone_violation_n,maximum_inequality:report.constraints.inequalities.reduce((a,b)=>Math.max(a,b),0),sampled_feasible:true,scope:'Passes the combined 1000+4000 uniform audit and event mesh under the original planner gates. Subsequent runtime rejection identifies missing servo-command constraints; this is not an executable gait or speed gain.'};
fs.writeFileSync(d+'joint-body16-domain4000.summary.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});
const gz=gzipSync(raw);assert(gunzipSync(gz).equals(raw));fs.writeFileSync(path+'.gz',gz,{flag:'wx'});
fs.writeFileSync(d+'joint-body16-domain4000-compression.json',JSON.stringify({raw_path:path,raw_bytes:raw.length,raw_sha256:crypto.createHash('sha256').update(raw).digest('hex'),gzip_path:path+'.gz',gzip_bytes:gz.length,gzip_sha256:crypto.createHash('sha256').update(gz).digest('hex'),roundtrip_byte_equal:true},null,2)+'\n',{flag:'wx'});
fs.renameSync(path,'runs/joint-domain-restore/joint-body16-domain4000.result.json');
console.log(JSON.stringify({...summary,attempts:x.attempts.length,gzip_bytes:gz.length}));
