import fs from 'node:fs';
import assert from 'node:assert/strict';
import {isDeepStrictEqual as equal} from 'node:util';
const d='examples/full-robot/contact-planning/';
const read=n=>JSON.parse(fs.readFileSync(d+n));
const same=(a,b,label)=>assert(equal(a,b),label);
const result=read('joint-body16-domain.result.json');
const target=read('joint-body16-conic-audit.recipe.json');
const reference=read('joint-conic-feasible-speed.recipe.json');
const r=result.restoration.restoration;
const [candidate,report]=r.evaluation;
assert.equal(result.restoration.reference_body_refinements,1);
assert(r.fraction>=0&&r.fraction<=1);
assert.equal(r.attempts[0].fraction,0);
assert.equal(r.attempts[0].rejection,null);
assert.equal(r.attempts[1].fraction,1);
if(r.rejected_upper_fraction!==null){
  assert(r.rejected_upper_fraction>r.fraction);
  assert(r.rejected_upper_fraction-r.fraction<=2**(-result.config.bisection_iterations));
  assert(r.attempts.some(a=>a.fraction===r.rejected_upper_fraction&&a.rejection!==null));
}
assert(r.attempts.some(a=>a.fraction===r.fraction&&a.rejection===null));
const expected=structuredClone(target); expected.candidate=candidate;
same(expected,result.restored_recipe,'Restoration changed target fields beyond candidate');
same(candidate.force_timing,target.candidate.force_timing,'Restoration changed contact timing bindings');
same(reference.robot,target.robot,'Input robot and physical gates differ');
const audit=structuredClone(result.restored_recipe);
audit.robot.uniform_samples=result.config.audit_uniform_samples;
audit.robot.additional_phases=[...new Set([...target.robot.additional_phases,...Array.from({length:target.robot.uniform_samples},(_,i)=>(i+.5)/target.robot.uniform_samples)])].sort((a,b)=>a-b);
same(audit,result.audit_recipe,'Dense audit changed fields beyond mesh');
assert.equal(r.values.length,target.variables.length);
for(let i=0;i<r.values.length;i++)assert(r.values[i]>=target.variables[i].bound.lower&&r.values[i]<=target.variables[i].bound.upper,'Selected decision outside original bound');
assert(report.motion_report.frames.length>=result.config.audit_uniform_samples*2);
assert(report.motion_report.frames.every(f=>f.maximum_inter_link_penetration_m===0&&f.maximum_floor_penetration_m<=target.robot.penetration_tolerance_m));
const summary={reference_body_refinements:result.restoration.reference_body_refinements,accepted_fraction:r.fraction,rejected_upper_fraction:r.rejected_upper_fraction,attempts:r.attempts,frames:report.motion_report.frames.length,speed_m_s:report.motion_report.speed_m_s,force_error_n:report.motion_report.maximum_force_error_n,moment_error_nm:report.motion_report.maximum_moment_error_nm,torque_margin_nm:report.motion_report.minimum_torque_margin_nm,cone_violation_n:report.maximum_cone_violation_n,maximum_inequality:Math.max(...report.constraints.inequalities),sampled_feasible:report.sampled_feasible,scope:'Dense sampled CAD/geometry domain recovered along the explicit parameter segment. No global or continuous-domain guarantee; no measured runtime speed gain.'};
fs.writeFileSync(d+'joint-body16-domain.summary.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(d+'joint-body16-domain.recipe.json',JSON.stringify(result.restored_recipe,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(d+'joint-body16-domain-audit.recipe.json',JSON.stringify(result.audit_recipe,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({...summary,attempts:r.attempts.length,target_rejection:r.attempts[1].rejection}));
