import fs from 'node:fs';
import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
import crypto from 'node:crypto';
const d='examples/full-robot/contact-planning/';
const source=d+'joint-body8-speed.recipe.json',artifact=d+'joint-force-alignment-checked.result.json';
const original=JSON.parse(fs.readFileSync(source)),r=JSON.parse(fs.readFileSync(artifact));
assert(original.candidate.force_templates.flat().every(t=>t.interpolation==='linear'));
assert.equal(r.linear_templates_checked,8);assert(r.maximum_linear_force_curve_change_n<1e-10);
const strip=recipe=>{const x=structuredClone(recipe);delete x.candidate.force_templates;x.variables=x.variables.filter(v=>v.decision.kind!=='force');return x;};
assert(isDeepStrictEqual(strip(original),strip(r.recipe)),'Changed motion, physical model, other decisions or search controls');
assert.equal(r.recipe.variables.length,443);assert.equal(r.report.sampled_feasible,false);
const output=d+'joint-aligned-speed.recipe.json',initial=d+'joint-aligned-speed-initial.result.json';
fs.writeFileSync(output,JSON.stringify(r.recipe,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(initial,JSON.stringify(r.report)+'\n',{flag:'wx'});
const summary=x=>({speed_m_s:x.motion_report.speed_m_s,frames:x.motion_report.frames.length,force_error_n:x.motion_report.maximum_force_error_n,moment_error_nm:x.motion_report.maximum_moment_error_nm,torque_margin_nm:x.motion_report.minimum_torque_margin_nm,cone_violation_n:x.maximum_cone_violation_n,maximum_inequality:Math.max(0,...x.constraints.inequalities),sampled_feasible:x.sampled_feasible});
const identity=path=>({path,bytes:fs.statSync(path).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex')});
fs.writeFileSync(d+'joint-force-alignment-preparation.json',JSON.stringify({inputs:[source,artifact].map(identity),outputs:[output,initial].map(identity),original:summary(r.original_report),refined_curves:summary(r.resampled_report),cad_initialized:summary(r.report),original_variables:original.variables.length,aligned_variables:r.recipe.variables.length,force_variables:r.recipe.variables.filter(v=>v.decision.kind==='force').length,nodes_per_clock:r.recipe.candidate.force_templates.map(t=>t.map(f=>f.keyframes.length)),maximum_linear_force_curve_change_n:r.maximum_linear_force_curve_change_n,curve_samples_per_template:r.curve_samples_per_template,non_force_recipe_identical:true,scope:'Exact refinement of the actual linear force curves, followed by explicit CAD load initialization. Added force freedom and audit phases; same body/foot motion, bounds, speed objective, 8000-evaluation budget and physical model. Initial report extraction canonicalizes signed zeros through JavaScript.'},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({variables:r.recipe.variables.length,original:summary(r.original_report),cad_initialized:summary(r.report),linear_curve_error:r.maximum_linear_force_curve_change_n}));
