import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const d='examples/full-robot/contact-planning/';
const id=path=>{const b=fs.readFileSync(path);return{path,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')};};
const read=p=>JSON.parse(fs.readFileSync(p));
const archive=(name,files)=>{const path=d+name;assert(!fs.existsSync(path));execFileSync('tar',['-czf',path,...files]);return{...id(path),entries:files.map(id)};};
const sourceFiles=['crates/sim-runtime/Cargo.toml','crates/sim-runtime/src/contact_planning/joint.rs','crates/sim-runtime/src/contact_planning/joint_ipopt.rs','crates/sim-runtime/examples/optimize_joint_ipopt.rs','crates/sim-runtime/examples/optimize_joint_ipopt_checkpoint.rs','crates/sim-runtime/examples/support/joint_checkpoint.rs','.github/workflows/native-ipopt.yml',d+'check_joint_checkpoints.mjs',d+'record_joint_checkpoints.mjs'];
const verificationFiles=[];
function walk(p){for(const entry of fs.readdirSync(p,{withFileTypes:true})){const path=p+'/'+entry.name;if(entry.isDirectory())walk(path);else verificationFiles.push(path);}}
walk('runs/joint-checkpoints/verification');
const runtimePrefix='runs/contact-planning/joint-mesh-command-screen';
const runtimeFiles=fs.readdirSync('runs/contact-planning').filter(n=>n.startsWith('joint-mesh-command-screen.')).sort().map(n=>'runs/contact-planning/'+n);
const capture=read(runtimePrefix+'.native.json');
assert(capture.completed&&capture.error===null&&capture.frames.length===401&&capture.frames.at(-1).time_s===8);
assert.equal(capture.recording.seed,0);
const measured=read(d+'joint-mesh-command-screen.summary.json'),clearance=read(d+'joint-mesh-command-clearance.summary.json');
assert.equal(measured.capture_sha256,id(runtimePrefix+'.native.json').sha256);
assert(measured.passed_control_checks&&measured.passed_contact_quality);
assert.equal(clearance.maximum_command_error_rad,0);assert.equal(clearance.passed_foot_clearances,20);
assert.equal(clearance.planned_foot_clearances,20);assert.equal(clearance.inter_link_geometry_audit.maximum_penetration_m,0);
const root='/Users/elliot/physics-simulator/target/gait-exploration/release/examples/';
const optimizer=id(root+'optimize_joint_ipopt_checkpoint');
const scene='runs/speed-ceiling/validation/constrained-front165-scale1-human-fine.scene.json';
const markers='examples/full-robot/gait-exploration/workspace-markers.json';
const inputPaths=[scene,markers,d+'joint-mesh-command-speed.recipe.json',d+'joint-mesh-command-speed.search.json'];
const completed=fs.readdirSync(d).filter(n=>n.startsWith('joint-checkpoint-')||n.startsWith('joint-mesh-command-')||n.startsWith('joint-conic-mesh-speed.')).filter(n=>!['joint-mesh-command-speed.log','joint-mesh-command-speed.result.json','joint-mesh-command-speed-launch.json','joint-checkpoint-build.json'].includes(n));
const manifest={base_commit:execFileSync('git',['rev-parse','HEAD']).toString().trim(),recorded_at:new Date().toISOString(),sources:archive('joint-checkpoint-sources.tar.gz',sourceFiles),verification:archive('joint-checkpoint-verification.tar.gz',verificationFiles),runtime:archive('joint-checkpoint-runtime.tar.gz',runtimeFiles),cargo_lock:id('Cargo.lock'),rustc:execFileSync('/Users/elliot/.cargo/bin/rustc',['-Vv']).toString(),optimizer,binaries:['solve_joint_force_cones','run_environment','replay_policy_state','evaluate_lift'].map(n=>id(root+n)),compiler:id('/Users/elliot/physics-simulator/target/gait-contact-timing/release/examples/compile_contact_reference'),previous_binary_provenance:[d+'joint-servo-conic-build.json',d+'joint-servo-command-build.json',d+'smooth-return-evidence-index.json'].map(id),native_library_manifest:id(d+'joint-ipopt-native-library.json'),inputs:inputPaths.map(id),durable_scene:{index:'examples/full-robot/speed-ceiling/evidence-v8-index.json',entry:'validation/constrained-front165-scale1-human-fine.scene.json'},completed_artifacts:completed.sort().map(n=>id(d+n)),terminal_exit_codes:{old_mesh_search:0,conic_final:0,conic_best:0,reference:0,runtime:0,runtime_analysis:0,clearance:0,checkpoint_verification:0,planner_tests:0,checkpoint_test:0,build:0},scope:'Passive snapshot smoke/replay verified; completed older local search and conic repair, dense compilation and short runtime screen retained. Current searches remain live. No faster gait, timestep/sustained/browser qualification or global maximum established.'};
fs.writeFileSync(d+'joint-checkpoint-build.json',JSON.stringify(manifest,null,2)+'\n',{flag:'wx'});
const launch={recorded_at:new Date().toISOString(),session_id:51018,optimizer,inputs:inputPaths.map(id),source_build:id(d+'joint-checkpoint-build.json'),command:[optimizer.path,scene,markers,d+'joint-mesh-command-speed.recipe.json','/Users/elliot/physics-simulator-gait-exploration/runs/native-ipopt-casadi-3.8.0/minimal/libipopt.dylib',d+'joint-mesh-command-speed.search.json','runs/joint-checkpoints/mesh-command-speed'],environment:{VECLIB_MAXIMUM_THREADS:'1',OMP_NUM_THREADS:'1'},stdout:d+'joint-mesh-command-speed.result.json',stderr:d+'joint-mesh-command-speed.log',status:'Launched and observed live; terminal output not parsed or archived.',scope:'Eight-control joint speed search from the conic-repaired current-command-bounded motion, with live candidate output. Numerical run budget is not a physical stopping certificate.'};
fs.writeFileSync(d+'joint-mesh-command-speed-launch.json',JSON.stringify(launch,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({source_archive_bytes:manifest.sources.bytes,verification_archive_bytes:manifest.verification.bytes,runtime_archive_bytes:manifest.runtime.bytes,optimizer,completed_artifacts:completed.length,session_id:51018}));
