// Terminal-result reducer only; all physical evaluation remains in Rust.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const prefix=process.argv[2];assert(prefix,'Pass a completed native search output prefix');
const path=prefix+'.result.json',r=JSON.parse(fs.readFileSync(path));
const summarize=report=>report?{speed_m_s:report.motion_report.speed_m_s,force_error_n:report.motion_report.maximum_force_error_n,moment_error_nm:report.motion_report.maximum_moment_error_nm,torque_margin_nm:report.motion_report.minimum_torque_margin_nm,cone_violation_n:report.maximum_cone_violation_n,maximum_inequality:Math.max(0,...report.constraints.inequalities),maximum_interlink_penetration_m:Math.max(0,...report.motion_report.frames.map(f=>f.maximum_inter_link_penetration_m)),maximum_floor_penetration_m:Math.max(0,...report.motion_report.frames.map(f=>f.maximum_floor_penetration_m)),sampled_feasible:report.sampled_feasible}:null;
assert(r.search&&r.initial_report&&Number.isInteger(r.model_evaluations),'Not a terminal joint Ipopt result');
const report={source:{path,bytes:fs.statSync(path).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex')},initial:summarize(r.initial_report),final:summarize(r.report),returned_candidate_error:r.returned_candidate_error,best_sampled_feasible_found:r.best_sampled_feasible!==null,model_evaluations:r.model_evaluations,model_budget_exhausted:r.model_budget_exhausted,native:{status:r.search.native_status,maximum_constraint_or_bound_violation:r.search.maximum_constraint_or_bound_violation,value_evaluations:r.search.value_evaluations,derivative_evaluations:r.search.derivative_evaluations,rejected_callbacks:r.search.rejected_callbacks,budget_exhausted:r.search.budget_exhausted,callback_panicked:r.search.callback_panicked,cancelled:r.search.cancelled,last_callback_error:r.search.last_callback_error,iterations:r.search.iterations},scope:'Completed local joint NLP result; native termination is not a physical infeasibility or optimality certificate. Physical summary comes from the independently audited returned candidate. No runtime/browser gait or global maximum established.'};
fs.writeFileSync(prefix+'.summary.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({...report,source:undefined,native:{...report.native,iterations:report.native.iterations.length}}));
