import fs from 'node:fs';import {recordedContactMotion} from '../../interactive/recorded_contact_motion.mjs';
const d='examples/full-robot/gait-exploration',read=p=>JSON.parse(fs.readFileSync(`${d}/${p}`));
const plan=read('steering-plan.json'),ref=read('steering-reference.native.json'),body=f=>f.poses.find(p=>p.name.includes('Chassis')),yaw=f=>Math.atan2(body(f).rotation[1][0],body(f).rotation[0][0]);
let rows=[];for(let v of plan.cases){let c=read(v.name+'.native.json'),fs=c.frames,near=t=>fs.reduce((a,b)=>Math.abs(b.time_s-t)<Math.abs(a.time_s-t)?b:a),p=f=>body(f).position_m;
 let windows=[[1.4,6,1],[11,16,-1]].map(([a,b,sign])=>{let x=near(a),y=near(b),h=yaw(x);return {start_s:a,end_s:b,directed_speed_mm_s:sign*1000*((p(y)[0]-p(x)[0])*Math.cos(h)+(p(y)[1]-p(x)[1])*Math.sin(h))/(y.time_s-x.time_s)}});
 let totalTravel=0;for(let i=1;i<fs.length;i++)totalTravel+=Math.hypot(p(fs[i])[0]-p(fs[i-1])[0],p(fs[i])[1]-p(fs[i-1])[1]);
 let feet=c.recording.config.policy.point_feedback.markers.map(m=>{let index=c.recording.scene.robot.links.findIndex(l=>l.name===m.link),samples=fs.map(f=>recordedContactMotion(f,index,m.link)),path=0;for(let i=1;i<samples.length;i++){let a=samples[i-1],b=samples[i];if(a.force>=1&&b.force>=1)path+=(b.time_s-a.time_s)*(a.speed+b.speed)/2}return {link:m.link,loaded_material_motion_m:path,motion_to_total_body_path_ratio:path/totalTravel}});
 let maximumBodyDifference=0;for(let i=0;i<Math.min(fs.length,ref.frames.length);i++)maximumBodyDifference=Math.max(maximumBodyDifference,Math.hypot(...p(fs[i]).map((x,k)=>x-p(ref.frames[i])[k])));
 let times=[...c.transition_wall_s].sort((a,b)=>a-b),row={name:v.name,completed:c.completed,error:c.error,final_time_s:fs.at(-1).time_s,windows,turn_rad:yaw(near(10))-yaw(near(6)),stop_drift_m:Math.hypot(p(near(20))[0]-p(near(16.4))[0],p(near(20))[1]-p(near(16.4))[1]),maximum_tilt_rad:Math.max(...fs.map(f=>Math.acos(Math.max(-1,Math.min(1,body(f).rotation[2][2]))))),total_horizontal_body_path_m:totalTravel,feet,maximum_matched_body_difference_from_reference_m:maximumBodyDifference,native:{wall_s:c.wall_s,simulation_per_wall:fs.at(-1).time_s/c.wall_s,p95_transition_s:times[Math.ceil(.95*times.length)-1]}};rows.push(row);
}
fs.writeFileSync(`${d}/steering-summary.json`,JSON.stringify({version:1,rows,scope:'20 s forward/walking-turn/reverse/stop development tests. Slip denominator is total body path because net displacement cancels under reversal; not comparable directly with straight-run net-advance ratios. Stop window allows 0.4 s to finish a swing; phase-gated stopping is not instantaneous. Full sampled geometry audit remains separate.'},null,2)+'\n');console.log(rows.map(r=>({name:r.name,completed:r.completed,speeds:r.windows.map(w=>w.directed_speed_mm_s),turn:r.turn_rad,stop_mm:r.stop_drift_m*1000,max_difference_mm:r.maximum_matched_body_difference_from_reference_m*1000,max_slip_ratio:Math.max(...r.feet.map(f=>f.motion_to_total_body_path_ratio)),native:r.native})));
