// Analytic screening and CAD/recording postprocessing; no alternate simulation.
import fs from 'node:fs';
const d='examples/full-robot/gait-exploration',read=p=>JSON.parse(fs.readFileSync(p));
const plan=read(`${d}/opposite-pair.plan.json`),scene=read(`${d}/opposite-pair.scene.json`),cfg=read(`${d}/opposite-pair.config.json`);
const poses=plan.frames[0].poses, mass=scene.robot.links.reduce((a,l)=>a+l.mass,0);
const com=[0,1,2].map(i=>scene.robot.links.reduce((s,l)=>s+l.mass*poses.find(p=>p.name===l.name).position_m[i],0)/mass);
const h=com[2]-scene.robot.world.floor_z,lambda=Math.sqrt(-scene.robot.gravity[2]/h),quarter=mass*9.81/4,pair=mass*9.81/2;
let inertia=Array.from({length:3},()=>[0,0,0]);
for(let l of scene.robot.links){let p=poses.find(p=>p.name===l.name),r=p.rotation,offset=p.position_m.map((x,i)=>x-com[i]),d2=offset.reduce((s,x)=>s+x*x,0);for(let i=0;i<3;i++)for(let j=0;j<3;j++){let rotated=0;for(let a=0;a<3;a++)for(let b=0;b<3;b++)rotated+=r[i][a]*l.inertia[a][b]*r[j][b];inertia[i][j]+=rotated+l.mass*((i===j?d2:0)-offset[i]*offset[j])}}
const ws=read(`${d}/workspace-results.json`).rows.find(x=>x.id==='coupled-same-hip0-foot-60');
let estimates=ws.markers.map((m,i)=>({foot:m.id,jacobian_m_per_rad:m.jacobian.map(r=>r.slice(3*i,3*i+3)),vertical_contact_torque_contribution_nm_for_equal_pair_support:m.jacobian[2].slice(3*i,3*i+3).map(j=>j*pair)}));
let peak=Array(12).fill(0);for(let i=1;i<plan.trajectory.keyframes.length;i++){let a=plan.trajectory.keyframes[i-1],b=plan.trajectory.keyframes[i];for(let j=0;j<12;j++)peak[j]=Math.max(peak[j],Math.abs((b.values[j]-a.values[j])/(b.time_s-a.time_s)))}
const out={version:1,cad_sha256:scene.robot.source.cad_sha256,mass_kg:mass,initial_crouched_com_world_m:com,com_height_above_floor_m:h,initial_centroidal_inertia_world_kg_m2:inertia,gravity_m_s2:-scene.robot.gravity[2],declared_floor_kinetic_friction:scene.robot.world.floor_friction,equal_four_support_load_n:quarter,equal_pair_support_load_n:pair,constant_height_lip_lambda_per_s:lambda,unsupported_horizontal_growth_cosh_over_024s:Math.cosh(lambda*.24),estimates,opposite_pair_peak_reference_speed_rad_s:peak,effective_servo_limits:cfg.motors.effective.components[0].parameters,formulas:{speed:'v = stride / full foot-cycle duration',centroidal_translation:'m * c_ddot = sum(f_i) + m*g',centroidal_rotation:'H_dot = sum((r_i-c) cross f_i)',unilateral_friction:'f_iz >= 0; ||f_i,xy|| <= mu_i*f_iz',velocity_mapping:'v_foot = v_base + omega cross r + J(q)*q_dot',contact_torque:'tau_contact = J(q)^T*f (only this contribution)',constant_height_screen:'lambda=sqrt(g/h); zero-momentum transverse error grows as cosh(lambda*t), absent support correction'},limitations:['CAD mass/inertia/material and actuator model remain provisional, not hardware calibrated.','Equal load split and initial-Jacobian torques are screening estimates, not a solved full-body force allocation or motor saturation proof.','This radial quadruped alternates opposite support lines; PLANC humanoid single-support momentum reset is not copied. Full centroidal force/moment balance is the adaptation target.','Reference-speed maxima exclude feedback and dynamic motor demand; stall torque and no-load speed cannot be demanded together.'],paper:'https://arxiv.org/html/2601.06286v1'};
fs.writeFileSync(`${d}/physics-derivation.json`,JSON.stringify(out,null,2)+'\n');console.log({mass,h,lambda,quarter,pair,estimates});
