import fs from 'node:fs';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {validateEntry} from '../../../web/viewer/leaderboard-model.mjs';
const d='examples/full-robot/gait-exploration',bundle='runs/gait-exploration/viewer',read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),valueHash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),source=p=>({path:p,sha256:sha(p)});
const c=read(`${d}/steering-5ms.native.json`),m=read(`${d}/steering-summary.json`).rows.find(x=>x.name==='steering-5ms'),b=read(`${d}/browser-live.json`),preset=read(`${d}/browser-preset.json`);
const gate=(status,detail)=>({status,detail});
const e={id:'fast-paired-gait',name:'Physics-derived opposite-pair gait',description:'20 s forward, walking-turn, reverse and stop trial. Short forward speed 27.1 mm/s; reverse 24.9 mm/s. Slip and rendered realtime latency remain failures.',benchmark_version:'paired-steering-development-20s-v1',controller_sha256:valueHash({controller:c.recording.scene.controller,policy:c.recording.config.policy}),model_sha256:valueHash(c.recording.scene.robot),cad_sha256:c.recording.scene.robot.source.cad_sha256,environment_sha256:valueHash(c.recording.scene.robot.world),fidelity_sha256:valueHash({options:c.recording.scene.options,step_s:.005}),fidelity_label:'Effective servo · 5 ms compared with 1.25 ms',environment_label:'Flat floor · no push',comparison_group:'paired-steering-development-20s-v1',load:{scene:source(`${d}/steering-5ms.scene.json`),config:source(`${d}/steering-5ms.config.json`),task:source(`${d}/live-pair.task.json`),seed:0,asset_sha256:preset.asset_sha256},replay:{completed_steps:c.recording.completed_steps,input_events:c.recording.input_events},metrics:{simulated_s:20,sustained_speed_m_s:null,speed_window_s:4.6,short_speed_m_s:m.windows[0].directed_speed_mm_s/1000,task_passed:false,qualified_swings:null,swings:null,final_heading_error_rad:null,final_position_error_m:null,positive_mechanical_work_j:null,native_throughput:m.native.simulation_per_wall,native_hardware:'Native development measurement; browser host in parity report.',browser_active_throughput:b.simulation_per_wall,browser_active_p95_s:b.p95_transition_s},gates:{sustained_walk:gate('missing','No minute-long qualified run.'),turn_reverse_stop:gate('pass','Completed 20 s requested forward/walking-turn/reverse/stop; 0.104 rad turn and 0.236 mm late stop drift.'),disturbances:gate('missing','No qualified robust controller; full-authority distilled student failed tilt at 3.28 s.'),terrain:gate('missing','Flat floor only.'),contact_motion:gate('fail','Worst loaded foot material motion / total body path is 10.9% during steering, above 5%. All 1001 recorded poses had no sampled inter-link overlap.'),numerical_accuracy:gate('missing','5 ms differs from 1.25 ms by at most 1.46 mm over 20 s; longer/finer validation remains open.'),browser_realtime:gate('fail',`Rendered active pace ${b.simulation_per_wall.toFixed(3)}x; p95 ${(1000*b.p95_transition_s).toFixed(1)} ms.`),replay_parity:gate('pass','20 s browser/native comparison and exact replay/reset passed.')},evidence:['steering-summary.json','steering-5ms.geometry.json','browser-parity.json','browser-live.json','student-observation-boundary.json','cad-point-check.json'].map(p=>source(`${d}/${p}`)),capture:source(`${d}/steering-5ms.native.json`),limitations:'Uncalibrated CAD physics and ideal joint sensing; no sim-to-real or stability guarantee. Walking turns, no turn-in-place or lateral motion.',preset_id:preset.id};
validateEntry(e);fs.writeFileSync(`${d}/leaderboard-entry.json`,JSON.stringify(e,null,2)+'\n');let board=read(`${bundle}/leaderboard.json`);board.entries.unshift(e);fs.writeFileSync(`${bundle}/leaderboard.json`,JSON.stringify(board)+'\n');
// Archive a minimal tested runtime/template so reconstruction never requires ignored runs.
let template='runs/gait-exploration/template';fs.mkdirSync(template,{recursive:true});for(let name of fs.readdirSync(bundle)){if(name==='data')continue;fs.cpSync(`${bundle}/${name}`,`${template}/${name}`,{recursive:true})}fs.writeFileSync(`${template}/catalog.json`,JSON.stringify({presets:[]}));fs.writeFileSync(`${template}/leaderboard.json`,JSON.stringify({version:1,entries:[e],scope:'Experimental 20 s paired-gait evidence; not ranked.'}));
let tar=spawnSync('tar',['-czf',`${process.cwd()}/${d}/browser-template.tar.gz`,'-C',template,'.']);if(tar.status!==0)throw Error('template archive failed');
const files=[];function walk(path=''){for(let name of fs.readdirSync(d+(path?'/'+path:''))){let rel=path?path+'/'+name:name,st=fs.statSync(d+'/'+rel);if(st.isDirectory())walk(rel);else if(st.size>262144&&!rel.endsWith('.tar.gz'))files.push(rel)}}walk();files.sort();
let index={version:1,files:files.map(p=>({path:p,bytes:fs.statSync(d+'/'+p).size,sha256:sha(d+'/'+p)})),scope:'Exact raw captures, recipes and inspection outputs archived durably. Restore from evidence.tar.gz before rerunning analysis scripts.'};fs.writeFileSync(`${d}/evidence-index.json`,JSON.stringify(index,null,2)+'\n');fs.writeFileSync(`${d}/evidence-files.txt`,files.join('\n')+'\n');fs.writeFileSync(`${d}/.gitignore`,files.map(p=>'/'+p).join('\n')+'\n');tar=spawnSync('tar',['-czf','evidence.tar.gz','-T','evidence-files.txt'],{cwd:d});if(tar.status!==0)throw Error('evidence archive failed');
fs.writeFileSync(`${d}/archive-sha256.json`,JSON.stringify(Object.fromEntries(['evidence.tar.gz','browser-template.tar.gz'].map(p=>[p,sha(d+'/'+p)])),null,2)+'\n');console.log({archived_files:files.length,archive_bytes:fs.statSync(d+'/evidence.tar.gz').size,template_bytes:fs.statSync(d+'/browser-template.tar.gz').size});
