import {spawnSync} from 'node:child_process';
import fs from 'node:fs';import crypto from 'node:crypto';
const source='/Users/elliot/physics-simulator/runs/interactive/causal-response/viewer',out='runs/gait-exploration/viewer',d='examples/full-robot/gait-exploration',read=p=>JSON.parse(fs.readFileSync(p));
if(fs.existsSync(`${d}/browser-template.tar.gz`)){fs.mkdirSync(out,{recursive:true});const r=spawnSync('tar',['-xzf',`${d}/browser-template.tar.gz`,'-C',out]);if(r.status!==0)throw Error('template extraction failed');}else{fs.cpSync(source,out,{recursive:true,mode:fs.constants.COPYFILE_FICLONE});}
fs.copyFileSync('web/viewer/viewer.js',`${out}/viewer.js`);fs.copyFileSync('web/viewer/motion-commands.mjs',`${out}/motion-commands.mjs`);
const id='experimental-fast-paired-gait',path=`data/${id}.json`,data={scene:read(`${d}/steering-5ms.scene.json`),config:read(`${d}/steering-5ms.config.json`),task:read(`${d}/live-pair.task.json`),seed:0};
fs.writeFileSync(`${out}/${path}`,JSON.stringify(data));const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const entry={id,label:'Experimental · Fast paired gait · 25 mm/s',mode:'embedded',path,task:`${d}/live-pair.task.json`,motion_commands:['command.forward_speed','command.lateral_speed','command.yaw_rate'],asset_sha256:hash(`${out}/${path}`),description:'Command-driven opposite-leg pairs. Hold W/S for forward/reverse; combine W or S with A/D for walking turns. Stop finishes an airborne transfer. No turn-in-place or lateral motion.',readiness:'Experimental: slip and realtime latency gates remain unmet.',evidence:'20 s native steering trial: 27.1 mm/s forward, 24.9 mm/s reverse. Explicit 5 ms approximation differs by at most 1.46 mm body position from the 1.25 ms reference. Ideal joint observations; uncalibrated CAD physics. Browser measurements pending.'};
let catalog=read(`${out}/catalog.json`);catalog.presets.unshift(entry);fs.writeFileSync(`${out}/catalog.json`,JSON.stringify(catalog,null,2)+'\n');let manifest=read(`${out}/build-manifest.json`);manifest.gait_exploration={reused_runtime_bundle:source,wasm_sha256:hash(`${out}/sim_web_bg.wasm`),inputs:Object.fromEntries([`${d}/steering-5ms.scene.json`,`${d}/steering-5ms.config.json`,`${d}/live-pair.task.json`,'web/viewer/viewer.js','web/viewer/motion-commands.mjs',`${out}/${path}`].map(p=>[p,hash(p)])),scope:'Existing proven shared runtime WASM reused without changing the original bundle. New Rhai/controller recipe and UI velocity-channel mapping; separate parity test required.'};fs.writeFileSync(`${out}/build-manifest.json`,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(`${d}/browser-preset.json`,JSON.stringify(entry,null,2)+'\n');console.log(out);
