import fs from 'node:fs';import assert from 'node:assert/strict';
const d='examples/full-robot/gait-exploration',read=p=>JSON.parse(fs.readFileSync(`${d}/${p}`));
const train=read('learning-teacher.native.json'),valid=read('learning-reserved-push.native.json');assert(train.completed&&valid.completed);
const config=structuredClone(train.recording.config),scene=structuredClone(train.recording.scene),features=[];
const add=(source,kind,scale,center=0)=>features.push({source,subtract:null,kind,scale,center,clip:5});
let centers={},outputs=config.motors.target_coordinates.map((name,i)=>{let bounds=config.policy.target_bounds_rad[name],target=name.replace(/^joint\./,'')+'.target';centers[target]=(bounds[0]+bounds[1])/2;let joint=name.replace(/^joint\./,'');add(joint+'.angle','Angle',i%3===0?.15:.3,config.initial_coordinates[i]);add(joint+'.angular_velocity','AngularVelocity',2);return {target,kind:'Angle',scale:(bounds[1]-bounds[0])/2}});
for(let axis of ['x','y','z']){add('body.gravity_direction.'+axis,'Dimensionless',.05,axis==='z'?-1:0);add('body.angular_velocity.'+axis,'AngularVelocity',.2)}
add('command.forward_speed','LinearVelocity',.025);add('command.lateral_speed','LinearVelocity',.025);add('command.yaw_rate','AngularVelocity',.2);
const hidden=64,network={version:1,features,outputs,layers:[{weights:Array.from({length:hidden},(_,i)=>features.map((_,j)=>.1*Math.sin((i+1)*(j+3)))),biases:Array(hidden).fill(0)},{weights:outputs.map(()=>Array(hidden).fill(0)),biases:outputs.map(()=>0)}]};
const sensors=features.map(f=>({name:f.source,kind:f.kind}));
const dataset=c=>({version:1,sensors,actuators:outputs.map(o=>({name:o.target,kind:o.kind})),samples:c.frames.filter(f=>f.policy).map(f=>({observations:sensors.map(s=>{let x=f.policy.observations[s.name];assert(Number.isFinite(x),s.name);return x}),actions:outputs.map(o=>f.policy.targets[o.target]-centers[o.target])}))});
config.motors.target_trajectory=null;config.policy.feedback_observations=false;config.policy.neural_residual=network;
scene.controller.sources={entry:'full-authority-student.rhai',files:{'full-authority-student.rhai':'fn control(t, sensors, commands, state) { let p = parameters(); for name in commands.keys() { commands[name] = p.centers[name]; } #{commands:commands,state:state} }'}};scene.controller.parameters={centers};
fs.writeFileSync(`${d}/student.initial.config.json`,JSON.stringify(config)+'\n');fs.writeFileSync(`${d}/student.scene.json`,JSON.stringify(scene)+'\n');
fs.writeFileSync(`${d}/student.experiment.json`,JSON.stringify({version:1,network,training:dataset(train),validation:dataset(valid),optimizer:{epochs:1000,learning_rate:.0005,batch_size:64}})+'\n');
fs.writeFileSync(`${d}/student-observation-boundary.json`,JSON.stringify({version:1,features:features.map(f=>f.source),motor_authority:'Complete motor targets over the declared exploration intervals, implemented as interval midpoint plus bounded neural output. No joint-reference or tiny-residual baseline.',teacher:'Physics-generated offline reference with ideal body/foot feedback; hand-designed teacher, not PPO-trained.',training:'Supervised Rust Adam; fixed teacher dataset. Reserved push states excluded from fitting and checkpoint selection.',excluded_network_inputs:['offline phase/time','joint reference targets','world body translation','foot positions','contact forces'],upstream_reference_dependency:false,declared_cad_sensors:scene.robot.sensors,deployable:false,limitations:['Joint and IMU-like observations remain ideal simulation diagnostics; CAD sensor bindings/noise/delay uncalibrated.','Supervised fit does not establish closed-loop gait stability.','Teacher learning and on-policy student robustness training remain outstanding.','Validation push is hypothetical 0.2 N for 0.2 s; not a calibrated robustness distribution.','Teacher capture wall times overlap a cancelled CAD export and are not standalone performance benchmarks.']},null,2)+'\n');
console.log({training_samples:dataset(train).samples.length,validation_samples:dataset(valid).samples.length,features:features.length,outputs:outputs.length});
