import fs from 'node:fs';
import crypto from 'node:crypto';
const dir='examples/full-robot/gait-exploration',name=process.argv[2];
if(!name)throw Error('candidate name required');
const plan=JSON.parse(fs.readFileSync(`${dir}/${name}.plan.json`));
const candidates=JSON.parse(fs.readFileSync(`${dir}/candidates.json`));
const def=candidates.definitions.find(x=>x.name===name);if(!def)throw Error('unknown candidate');
const config=JSON.parse(fs.readFileSync('examples/full-robot/whole-swing/settled-integral-minute.config.json'));
const scene=JSON.parse(fs.readFileSync('examples/full-robot/whole-swing/settled-integral-candidate.scene.json'));
const task=JSON.parse(fs.readFileSync('examples/full-robot/heading-task/task.json'));
delete task.walking;
const removed=new Set(task.observations.filter(o=>o.source.kind==='neural_correction').map(o=>o.name));
task.observations=task.observations.filter(o=>!removed.has(o.name));
task.rewards=task.rewards.filter(r=>!removed.has(r.observation));
task.termination_bounds=[{observation:'body.position.z',lower:plan.frames[0].poses.find(p=>p.name.includes('Chassis')).position_m[2]-.05,upper:.02},{observation:'body.up.z',lower:Math.cos(.1),upper:1.000000001}];
config.initial_coordinates=plan.trajectory.keyframes[0].values;
config.initial_base_translation_m=def.initial_base_translation_m;
config.steps=Math.round(def.duration_s/config.step_s);config.world_loads=null;
config.policy.step_reference=null;config.policy.neural_residual=null;
config.motors.target_trajectory=plan.trajectory;
config.motors.servos.forEach((s,i)=>s.target_rad=config.initial_coordinates[i]);
config.policy.target_bounds_rad=Object.fromEntries(plan.independent_coordinates.map((n,i)=>[n,[plan.config.bounds[i].lower,plan.config.bounds[i].upper]]));
let first=plan.frames[0];let initialBody=first.poses.find(p=>p.name.includes('Chassis')).position_m;
config.policy.body_feedback.position_world_m={interpolation:'linear',keyframes:plan.config.base_displacements_world_m.keyframes.map(k=>({time_s:k.time_s,values:k.values.map((x,i)=>x+initialBody[i])}))};
config.policy.point_feedback.position_world_m={interpolation:'linear',keyframes:plan.config.displacements_world_m.keyframes.map(k=>({time_s:k.time_s,values:k.values.map((x,i)=>x+first.marker_positions_world_m[Math.floor(i/3)][i%3])}))};
config.policy.point_feedback.activation={interpolation:'linear',keyframes:plan.config.displacements_world_m.keyframes.map(k=>({time_s:k.time_s,values:[0,1,2,3].map(i=>k.values[3*i+2]>1e-6?0:1)}))};
scene.controller.sources={entry:'physics-reference.rhai',files:{'physics-reference.rhai':'fn control(t, sensors, commands, state) { for name in commands.keys() { let joint = name.sub_string(0, name.len() - 7); let reference = sensors[joint + ".reference"]; commands[name] = reference + sensors["command.tracking_gain"] * (reference - sensors[joint + ".angle"]) + sensors["command.body_gain"] * sensors[joint + ".body_correction"] + sensors["command.point_gain"] * sensors[joint + ".point_correction"]; } #{commands: commands, state: state} }'}};
scene.controller.parameters={};
scene.controller.inputs=scene.controller.inputs.map(c=>c.name==='command.forward_speed'?{...c,upper:.1,initial:def.predicted_schedule_speed_mm_s/1000}:c);
scene.duration_s=def.duration_s;
const paths={scene:`${dir}/${name}.scene.json`,config:`${dir}/${name}.config.json`,task:`${dir}/${name}.task.json`};
for(let [k,p] of Object.entries(paths))fs.writeFileSync(p,JSON.stringify({scene,config,task}[k])+'\n');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
fs.writeFileSync(`${dir}/${name}.trial-provenance.json`,JSON.stringify({version:1,definition:def,paths,sha256:Object.fromEntries([...Object.values(paths),`${dir}/${name}.plan.json`,'/Users/elliot/physics-simulator/target/gait-exploration/release/examples/run_environment'].map(p=>[p,sha(p)])),notes:['CAD robot and effective actuators unchanged. Explicit crouched initial state and wider policy bounds.','No online stepping or step-qualified reward: offline joint/body/foot references through shared Rust runtime and Rhai feedback.','No neural residual; this is a physics-reference teacher candidate, not a trained controller.','Original minute task body-Z termination translated for lower posture; prospective tilt/speed/slip/stop screening is in candidates.json.']},null,2)+'\n');
console.log(paths);
