//! The catalogue's data: one `OpEntry` per cad-modify operation, with
//! RoboCAD's ids, labels, categories, keys, prompts, defaults, ranges and
//! messages, each citing its RoboCAD source (paths under `cad/robocad/`).
//!
//! Where RoboCAD says nothing (a handler that silently does nothing on an
//! empty selection), the refusal is a plain sentence of ours; those are
//! marked "(ours)" in `source`. Ranges are the dialog's (`QInputDialog`,
//! `QSpinBox`); the tools' `NumericField`s have none. `decimals` is the
//! dialog's, else 6 (what the viewer sends: rounded to 1e-6).
use super::*;
use super::kinds::*;
use crate::ui_kit::form::Unit;

/// Every operation, in RoboCAD's registry order (`ui/app.py` `_build_commands`),
/// then the REST-only `Ops` methods (`ops.<name>`).
pub(crate) static CATALOGUE: &[OpEntry] = &[
    // ---- Edit ---------------------------------------------------------------
    OpEntry {
        id: "edit.delete",
        label: "Delete",
        category: "Edit",
        keys: &["Delete", "Backspace"],
        needs: ANY_NODES,
        route: "delete",
        args: &[Arg::Nodes],
        refusal: "Select the nodes to delete",
        clears_selection: true,
        source: "ui/app.py:293 (label ui/strings.py:14), ui/app.py:1458-1463 (one Ops.delete of every selected node, then the selection is cleared; silent when empty: refusal ours), commands.py:312",
        ..BASE
    },
    OpEntry {
        id: "edit.copy",
        label: "Copy with Placement",
        category: "Edit",
        keys: &["Ctrl+C"],
        needs: ANY_NODES,
        route: "clipboard",
        shape: Shape::Copy,
        refusal: "Select the nodes to copy",
        source: "ui/app.py:294 (label ui/strings.py:14), ui/app.py:1465-1468 (Document.copy_nodes of the selected nodes; RoboCAD copies an empty clip: refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "edit.paste",
        label: "Paste with Placement",
        category: "Edit",
        keys: &["Ctrl+V"],
        route: "paste",
        shape: Shape::Paste,
        refusal: "Nothing to paste: copy with placement first (Ctrl+C)",
        source: "ui/app.py:295 (label ui/strings.py:14), ui/app.py:1470-1484 (paste_nodes keep_placement, one undo step \"Paste\"; RoboCAD's refusal \"Clipboard has no robocad content\" reads the system clipboard, the viewer's is its last copy)",
        ..BASE
    },
    // ---- Create: RoboCAD's PrimitiveTool -------------------------------------
    OpEntry {
        id: "tool.box",
        label: "Box (corner)",
        category: "Create",
        keys: &["Shift+A, B"],
        params: &[WIDTH, DEPTH, HEIGHT, p("corner", "corner", POINT, "0, 0, 0")],
        flow: Flow::Place(Primitive::BoxCorner),
        route: "box",
        shape: Shape::Place(Primitive::BoxCorner),
        hint: HINT_CORNER,
        source: "ui/app.py:328, ui/tools.py:391-536 (_finish :491, _make_box :517, commit :522; the anchor is the drag's first point or the plane origin); sent as Ops.box (commands.py:419) on the XY plane where RoboCAD extrudes a sketch rectangle",
        ..BASE
    },
    OpEntry {
        id: "tool.box_center",
        label: "Box (centre)",
        category: "Create",
        params: &[WIDTH, DEPTH, HEIGHT, p("center", "centre", POINT, "0, 0, 0")],
        flow: Flow::Place(Primitive::BoxCentre),
        route: "box",
        shape: Shape::Place(Primitive::BoxCentre),
        hint: HINT_CENTRE,
        source: "ui/app.py:329, ui/tools.py:522-529 (centred in the plane only, base on the plane; not Ops.box_center, which also centres the height); sent as Ops.box (commands.py:419)",
        ..BASE
    },
    OpEntry {
        id: "tool.cylinder",
        label: "Cylinder",
        category: "Create",
        keys: &["Shift+A, C"],
        params: &[DIAMETER, HEIGHT, p("base", "base centre", POINT, "0, 0, 0")],
        flow: Flow::Place(Primitive::Cylinder),
        route: "cylinder",
        shape: Shape::Place(Primitive::Cylinder),
        hint: HINT_CORNER,
        source: "ui/app.py:330, ui/tools.py:501-505 (_finish: axis ± the plane normal by the height's sign, radius at least 1e-3), commands.py:437",
        ..BASE
    },
    OpEntry {
        id: "tool.sphere",
        label: "Sphere",
        category: "Create",
        keys: &["Shift+A, S"],
        params: &[DIAMETER, p("center", "centre", POINT, "0, 0, 0")],
        flow: Flow::Place(Primitive::Sphere),
        route: "sphere",
        shape: Shape::Place(Primitive::Sphere),
        hint: HINT_CORNER,
        source: "ui/app.py:331, ui/tools.py:506-508 and :531-532, commands.py:440",
        ..BASE
    },
    // ---- Modify: fillets and chamfer (EdgeTool) --------------------------------
    OpEntry {
        id: "tool.fillet",
        label: "Fillet",
        keys: &["Ctrl+F"],
        needs: EDGES,
        params: &[p("radius", "radius", LENGTH, "1.0")],
        flow: Flow::PickThenForm(SelectMode::Edge),
        route: "fillet",
        args: &[Arg::Node, Arg::Edges, Arg::Param("radius")],
        fan: Fan::PerNode,
        refusal: NO_EDGES,
        hint: "fillet: select edges (click adds) then type the size • Enter applies",
        clears_selection: true,
        source: "ui/app.py:338, ui/tools.py:937-989 (fields :948, one call per node :977-985, selection cleared :986), commands.py:630",
        ..BASE
    },
    OpEntry {
        id: "tool.fillet_variable",
        label: "Variable fillet",
        needs: EDGES,
        params: &[p("radius", "start radius", LENGTH, "1.0"), p("radius_end", "end radius", LENGTH, "2.0")],
        flow: Flow::PickThenForm(SelectMode::Edge),
        route: "fillet",
        args: &[Arg::Node, Arg::Edges, Arg::Param("radius"), Arg::Param("radius_end")],
        fan: Fan::PerNode,
        refusal: NO_EDGES,
        hint: "variable: select edges (click adds) then type the size • Enter applies",
        clears_selection: true,
        source: "ui/app.py:339, ui/tools.py:948 and :980-981, commands.py:630",
        ..BASE
    },
    OpEntry {
        id: "tool.fillet_chordal",
        label: "Chordal fillet",
        needs: EDGES,
        params: &[p("chord", "chord", LENGTH, "1.0")],
        flow: Flow::PickThenForm(SelectMode::Edge),
        route: "fillet_chordal",
        args: &[Arg::Node, Arg::Edges, Arg::Param("chord")],
        fan: Fan::PerNode,
        refusal: NO_EDGES,
        hint: "chordal: select edges (click adds) then type the size • Enter applies",
        clears_selection: true,
        source: "ui/app.py:340, ui/tools.py:948 and :982-983, commands.py:633",
        ..BASE
    },
    OpEntry {
        id: "tool.fillet_all",
        label: "Fillet all edges…",
        needs: ANY_NODES,
        params: &[p("radius", "Radius (mm):", number(Unit::Length, 0.01, 100.0, 3), "1.0")],
        flow: Flow::Form,
        route: "fillet_all",
        args: &[Arg::Node, Arg::Param("radius")],
        fan: Fan::PerNode,
        refusal: "Select the bodies to fillet",
        source: "ui/app.py:341, ui/app.py:832-837 (getDouble \"Fillet all edges\", 1.0, 0.01..100, 3 decimals; silent with nothing selected: refusal ours), commands.py:636",
        ..BASE
    },
    OpEntry {
        id: "tool.full_round",
        label: "Full round (two edges)",
        needs: Needs::Edges { min: 2, max: Some(2), same_node: true },
        route: "full_round",
        args: &[Arg::Node, Arg::EdgeA, Arg::EdgeB],
        refusal: "Select two edges of the same body",
        source: "ui/app.py:342, ui/app.py:839-846, commands.py:639",
        ..BASE
    },
    OpEntry {
        id: "tool.remove_fillets",
        label: "Remove fillets (selected faces)",
        needs: FACES,
        route: "remove_fillets",
        args: &[Arg::Node, Arg::Faces],
        fan: Fan::PerNode,
        refusal: "Select the fillet faces to remove",
        source: "ui/app.py:343, ui/app.py:848-855 (faces grouped by node; silent when none: refusal ours), commands.py:642",
        ..BASE
    },
    OpEntry {
        id: "tool.chamfer",
        label: "Chamfer",
        keys: &["Ctrl+Shift+F"],
        needs: EDGES,
        params: &[p("distance", "distance", LENGTH, "1.0"), p("angle", "angle", ANGLE, "45.0")],
        flow: Flow::PickThenForm(SelectMode::Edge),
        route: "chamfer",
        shape: Shape::Chamfer,
        args: &[Arg::Node, Arg::Edges],
        fan: Fan::PerNode,
        refusal: NO_EDGES,
        hint: "chamfer: select edges (click adds) then type the size • Enter applies",
        clears_selection: true,
        source: "ui/app.py:344, ui/tools.py:948 and :984-985 (ChamferSpec, angle only when not 45°), commands.py:645",
        ..BASE
    },
    OpEntry {
        id: "tool.shell",
        label: "Hollow / shell",
        keys: &["Ctrl+Shift+H"],
        needs: Needs::NodesWithFaces,
        params: &[p("wall", "wall", LENGTH, "2.0")],
        flow: Flow::PickThenForm(SelectMode::Face),
        route: "shell",
        args: &[Arg::Node, Arg::Param("wall"), Arg::Faces],
        fan: Fan::PerNode,
        refusal: "Select a body or its faces to open",
        hint: "Select the faces to open (click adds), then type the wall thickness",
        clears_selection: true,
        source: "ui/app.py:345, ui/tools.py:992-1017, commands.py:624",
        ..BASE
    },
    OpEntry {
        id: "tool.thicken",
        label: "Thicken sheet…",
        needs: nodes(1, None, &["sheet"]),
        params: &[p("thickness", "Thickness (mm):", number(Unit::Length, 0.01, 100.0, 3), "2.0")],
        flow: Flow::Form,
        route: "thicken",
        args: &[Arg::Node, Arg::Param("thickness")],
        fan: Fan::PerNode,
        refusal: "Select a sheet",
        source: "ui/app.py:346, ui/app.py:857-864, commands.py:627",
        ..BASE
    },
    OpEntry {
        id: "tool.draft",
        label: "Draft faces…",
        needs: FACES,
        params: &[p("angle", "Angle (degrees):", number(Unit::Angle, -45.0, 45.0, 2), "2.0"), p("neutral", "neutral plane", PLANES, "xy")],
        flow: Flow::Form,
        route: "draft",
        args: &[Arg::Node, Arg::Faces, Arg::Const("[0, 0, 1]"), Arg::Param("angle"), Arg::Param("neutral")],
        fan: Fan::PerNode,
        refusal: "Select faces to draft",
        source: "ui/app.py:347, ui/app.py:866-878 (pull (0, 0, 1); neutral the active plane or XY: the plane is a parameter here), commands.py:553",
        ..BASE
    },
    OpEntry {
        id: "tool.delete_face",
        label: "Delete faces (heal)",
        needs: FACES,
        route: "delete_faces",
        args: &[Arg::Node, Arg::Faces],
        fan: Fan::PerNode,
        refusal: "Select the faces to delete",
        clears_selection: true,
        source: "ui/app.py:348, ui/app.py:880-887 (silent when none: refusal ours), commands.py:556",
        ..BASE
    },
    // ---- Modify: mirror, instance, array ---------------------------------------
    OpEntry {
        id: "tool.mirror",
        label: "Mirror (about active plane)",
        keys: &["Ctrl+M"],
        needs: ANY_NODES,
        params: &[p("plane", "mirror plane", PLANES, "yz")],
        route: "mirror",
        args: &[Arg::Nodes, Arg::Param("plane")],
        kwargs: &[("live", Arg::Const("false"))],
        refusal: "Select bodies to mirror",
        source: "ui/app.py:360, ui/app.py:910-914 (the active plane or YZ), commands.py:694",
        ..BASE
    },
    OpEntry {
        id: "tool.mirror_live",
        label: "Mirror as live instance",
        needs: ANY_NODES,
        params: &[p("plane", "mirror plane", PLANES, "yz")],
        route: "mirror",
        args: &[Arg::Nodes, Arg::Param("plane")],
        kwargs: &[("live", Arg::Const("true"))],
        refusal: "Select bodies to mirror",
        source: "ui/app.py:361, ui/app.py:910-914, commands.py:694",
        ..BASE
    },
    OpEntry {
        id: "tool.instance",
        label: "Instance selected",
        needs: ANY_NODES,
        route: "instance",
        args: &[Arg::Node, Arg::Const("{\"translation\": [20.0, 0.0, 0.0]}")],
        fan: Fan::PerNode,
        refusal: "Select the bodies to instance",
        source: "ui/app.py:364, ui/app.py:916-918 (Transform((20, 0, 0)) per node; silent when none: refusal ours), commands.py:712",
        ..BASE
    },
    OpEntry {
        id: "tool.array",
        label: "Array…",
        keys: &["Ctrl+Shift+A"],
        needs: ANY_NODES,
        params: &[
            p("kind", "Kind", FieldKind::Choice { options: &["rectangular", "radial"] }, "rectangular"),
            when(p("count_x", "Count X", number(Unit::Count, 1.0, 500.0, 0), "3"), "kind", "rectangular"),
            when(p("count_y", "Count Y", number(Unit::Count, 1.0, 500.0, 0), "1"), "kind", "rectangular"),
            when(p("count_z", "Count Z", number(Unit::Count, 1.0, 500.0, 0), "1"), "kind", "rectangular"),
            when(p("mode", "Mode", FieldKind::Choice { options: &["count + spacing", "count + total extent"] }, "count + spacing"), "kind", "rectangular"),
            when(p("spacing", "Spacing or extent X / Y / Z", POINT, "10, 10, 10"), "kind", "rectangular"),
            when(p("count", "Radial count", number(Unit::Count, 2.0, 360.0, 0), "6"), "kind", "radial"),
            when(p("angle", "Radial total angle", ANGLE, "360"), "kind", "radial"),
            when(p("plane", "axis plane (its normal through its origin)", PLANES, "xy"), "kind", "radial"),
            p("as_instances", "As live instances", CHECK, "false"),
            p("merge", "Merge into one body", CHECK, "false"),
        ],
        flow: Flow::Form,
        route: "array_rect",
        shape: Shape::Array,
        refusal: "Select bodies to array",
        source: "ui/app.py:365, ui/app.py:920-941 (radial about the active plane or XY), ui/widgets.py:1024-1053 (ArrayDialog), commands.py:728 and :738",
        ..BASE
    },
    // ---- Modify: cut, split, imprint, project, silhouette ----------------------
    OpEntry {
        id: "tool.cut_plane",
        label: "Cut with active plane",
        needs: ANY_NODES,
        params: &[p("plane", "cutting plane", PLANES, "xy")],
        route: "cut",
        args: &[Arg::Node, Arg::Param("plane")],
        fan: Fan::PerNode,
        refusal: "Select the bodies to cut",
        source: "ui/app.py:366, ui/app.py:943-945 (the active plane or XY; silent when none: refusal ours), commands.py:591",
        ..BASE
    },
    OpEntry {
        id: "tool.cut_sheet",
        label: "Cut with selected sheet/curve",
        needs: nodes(2, None, &[]),
        route: "cut",
        args: &[Arg::Target, Arg::Second],
        refusal: "Select the body, then the cutter",
        source: "ui/app.py:367, ui/app.py:947-951, commands.py:591",
        ..BASE
    },
    OpEntry {
        id: "tool.split_face",
        label: "Split faces with active plane",
        needs: ANY_NODES,
        params: &[p("plane", "splitting plane", PLANES, "xy")],
        route: "split_face",
        args: &[Arg::Node, Arg::Param("plane")],
        fan: Fan::PerNode,
        refusal: "Select the bodies whose faces to split",
        source: "ui/app.py:368, ui/app.py:953-955 (the active plane or XY; refusal ours), commands.py:566",
        ..BASE
    },
    OpEntry {
        id: "tool.imprint",
        label: "Imprint selected curve/body",
        needs: nodes(2, None, &[]),
        route: "imprint",
        args: &[Arg::Target, Arg::Second],
        refusal: "Select the body, then the tool",
        source: "ui/app.py:369, ui/app.py:957-961, commands.py:562",
        ..BASE
    },
    OpEntry {
        id: "tool.project_curve",
        label: "Project curve onto body",
        needs: nodes(2, None, &[]),
        params: &[p("direction", "direction (the view's when empty)", POINT, "")],
        route: "project_curve",
        args: &[Arg::Target, Arg::Second, Arg::ViewDir],
        refusal: "Select the curve/sketch, then the body",
        source: "ui/app.py:370, ui/app.py:963-968 (along the camera's view direction, -basis()[2]), commands.py:856",
        ..BASE
    },
    OpEntry {
        id: "tool.silhouette",
        label: "Silhouette onto active plane",
        needs: ANY_NODES,
        params: &[p("plane", "projection plane", PLANES, "xy")],
        route: "silhouette",
        args: &[Arg::Node, Arg::Param("plane")],
        fan: Fan::PerNode,
        refusal: "Select the bodies to project",
        source: "ui/app.py:371, ui/app.py:970-972 (the active plane or XY; refusal ours), commands.py:860",
        ..BASE
    },
    // ---- Advanced ---------------------------------------------------------------
    OpEntry {
        id: "tool.control_points",
        label: "Show/edit control points (advanced)",
        category: "Advanced",
        needs: FACES,
        route: "control_points",
        shape: Shape::ControlPoints,
        refusal: "Select a face",
        source: "ui/app.py:372, ui/app.py:974-984 (the first selected face's kernel.control_points, drawn as points and rows)",
        ..BASE
    },
    OpEntry {
        id: "tool.raise_degree",
        label: "Raise face degree",
        category: "Advanced",
        needs: FACES,
        route: "raise_degree",
        args: &[Arg::Node, Arg::Face, Arg::Const("4"), Arg::Const("4")],
        refusal: "Select a face to raise its degree",
        source: "ui/app.py:373, ui/app.py:986-991 (the first selected face, du = dv = 4; silent without a face: refusal ours), commands.py:867",
        ..BASE
    },
    OpEntry {
        id: "tool.rebuild_face",
        label: "Rebuild face…",
        category: "Advanced",
        needs: FACES,
        params: &[p("spans", "Spans per direction:", number(Unit::Count, 1.0, 64.0, 0), "4")],
        flow: Flow::Form,
        route: "rebuild_face",
        args: &[Arg::Node, Arg::Face, Arg::Param("spans"), Arg::Param("spans")],
        refusal: "Select a face to rebuild",
        source: "ui/app.py:374, ui/app.py:993-1001 (getInt \"Rebuild face\", 4, 1..64; silent without a face: refusal ours), commands.py:870",
        ..BASE
    },
    OpEntry {
        id: "tool.dependent_offset",
        label: "Dependent offset (face to body)…",
        needs: Needs::FaceThenNode,
        params: &[p("clearance", "Clearance (mm):", number(Unit::Length, -10.0, 10.0, 2), "0.2")],
        flow: Flow::Form,
        route: "offset_face_to",
        args: &[Arg::Node, Arg::Face, Arg::OtherNode, Arg::Param("clearance")],
        refusal: "Select a face, then the body to offset it to",
        source: "ui/app.py:375, ui/app.py:1003-1013, commands.py:521",
        ..BASE
    },
    OpEntry {
        id: "tool.set_pivot",
        label: "Set pivot at cursor snap",
        category: "Tools",
        needs: ANY_NODES,
        params: &[p("point", "point (the cursor snap when empty)", POINT, "")],
        flow: Flow::AtCursorSnap,
        route: "set_pivot",
        args: &[Arg::Target, Arg::CursorSnap],
        refusal: "Select the node whose pivot to set",
        source: "ui/app.py:376, ui/app.py:1015-1020 (the first selected node, the snap under the cursor; silent when none: refusal ours), commands.py:351",
        ..BASE
    },
    // ---- Modify: booleans, region, join ----------------------------------------
    OpEntry {
        id: "modify.union",
        label: "Union",
        keys: &["Ctrl+U"],
        needs: Needs::TargetThenTools,
        route: "boolean",
        args: &[Arg::Target, Arg::Tools, Arg::Const("\"union\"")],
        refusal: "Select the target body first, then the tools",
        clears_selection: true,
        source: "ui/app.py:382, ui/app.py:787-793, commands.py:573",
        ..BASE
    },
    OpEntry {
        id: "modify.subtract",
        label: "Subtract",
        keys: &["Ctrl+Shift+U"],
        needs: Needs::TargetThenTools,
        route: "boolean",
        args: &[Arg::Target, Arg::Tools, Arg::Const("\"subtract\"")],
        refusal: "Select the target body first, then the tools",
        clears_selection: true,
        source: "ui/app.py:383, ui/app.py:787-793, commands.py:573",
        ..BASE
    },
    OpEntry {
        id: "modify.intersect",
        label: "Intersect",
        keys: &["Ctrl+Alt+U"],
        needs: Needs::TargetThenTools,
        route: "boolean",
        args: &[Arg::Target, Arg::Tools, Arg::Const("\"intersect\"")],
        refusal: "Select the target body first, then the tools",
        clears_selection: true,
        source: "ui/app.py:384, ui/app.py:787-793, commands.py:573",
        ..BASE
    },
    OpEntry {
        id: "modify.region",
        label: "Region (overlap as new body)",
        needs: nodes(2, Some(2), &[]),
        route: "region",
        args: &[Arg::Target, Arg::Second],
        refusal: "Select exactly two bodies",
        source: "ui/app.py:385, ui/app.py:795-799, commands.py:588",
        ..BASE
    },
    OpEntry {
        id: "modify.join",
        label: "Join",
        keys: &["J"],
        needs: nodes(2, None, &[]),
        route: "join",
        args: &[Arg::Nodes],
        refusal: "Select two or more bodies to join",
        source: "ui/app.py:386 (Ops.join of the selected nodes, unchecked: refusal ours), commands.py:806",
        ..BASE
    },
    OpEntry {
        id: "modify.unjoin",
        label: "Unjoin",
        keys: &["Shift+J"],
        needs: ANY_NODES,
        route: "unjoin",
        args: &[Arg::Node],
        fan: Fan::PerNode,
        refusal: "Select the bodies to unjoin",
        source: "ui/app.py:387 (one call per node; refusal ours), commands.py:814",
        ..BASE
    },
    OpEntry {
        id: "modify.dissolve",
        label: "Dissolve redundant topology",
        needs: ANY_NODES,
        route: "dissolve",
        args: &[Arg::Node],
        fan: Fan::PerNode,
        refusal: "Select the bodies to dissolve",
        source: "ui/app.py:388 (one call per node; refusal ours), commands.py:823",
        ..BASE
    },
    OpEntry {
        id: "modify.make_unique",
        label: "Make instance unique",
        needs: nodes(1, None, &["instance"]),
        route: "make_unique",
        args: &[Arg::Node],
        fan: Fan::PerNode,
        refusal: "Select an instance to make unique",
        source: "ui/app.py:389 (instances only, others skipped silently: refusal ours), commands.py:719",
        ..BASE
    },
    // ---- Inspect (read-only overlays) -------------------------------------------
    OpEntry {
        id: "inspect.curvature",
        label: "Curvature comb on selected curve",
        category: "Inspect",
        needs: nodes(1, None, &["curve", "sketch"]),
        route: "curvature_comb",
        shape: Shape::CurvatureComb,
        refusal: "Select a curve or sketch",
        source: "ui/app.py:401, ui/app.py:1277-1284 (each selected curve or sketch; the last one's comb stays drawn; silent otherwise: refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "inspect.continuity",
        label: "Continuity check (G0/G1/G2)",
        category: "Inspect",
        needs: ANY_NODES,
        route: "continuity",
        shape: Shape::Continuity,
        refusal: "Select a body",
        source: "ui/app.py:402, ui/app.py:1286-1300 (each selected body; the last one's report stays drawn; refusal ours)",
        ..BASE
    },
    // ---- REST-only Ops methods (no RoboCAD command) -------------------------------
    OpEntry {
        id: "ops.box",
        label: "Box (corner and size)",
        category: "Create",
        params: &[p("corner", "corner", POINT, "0, 0, 0"), p("size", "size", POINT, "20, 20, 10")],
        flow: Flow::Form,
        route: "box",
        args: &[Arg::Param("corner"), Arg::Param("size")],
        source: "commands.py:419 (defaults: PrimitiveTool's anchor and box fields, ui/tools.py:411-413 and :524)",
        ..BASE
    },
    OpEntry {
        id: "ops.box_center",
        label: "Box (centre and size)",
        category: "Create",
        params: &[p("center", "centre", POINT, "0, 0, 0"), p("size", "size", POINT, "20, 20, 10")],
        flow: Flow::Form,
        route: "box_center",
        args: &[Arg::Param("center"), Arg::Param("size")],
        source: "commands.py:422 (centred in all three axes; defaults as ops.box)",
        ..BASE
    },
    OpEntry {
        id: "ops.box_three_point",
        label: "Box (three points and height)",
        category: "Create",
        params: &[p("a", "first base corner", POINT, ""), p("b", "second corner (along x)", POINT, ""), p("c", "point setting the width", POINT, ""), p("height", "height", LENGTH, "")],
        flow: Flow::Form,
        route: "box_three_point",
        args: &[Arg::Param("a"), Arg::Param("b"), Arg::Param("c"), Arg::Param("height")],
        source: "commands.py:426 (no defaults: each is required)",
        ..BASE
    },
    OpEntry {
        id: "ops.bridge",
        label: "Bridge two curves",
        category: "Create",
        needs: nodes(2, Some(2), &["curve", "sketch"]),
        route: "bridge",
        args: &[Arg::Target, Arg::Second],
        refusal: "Select two curves or sketches to bridge",
        source: "commands.py:511 (refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.move_faces",
        label: "Move faces",
        needs: FACES,
        params: &[p("translation", "translation", POINT, "")],
        flow: Flow::Form,
        route: "move_faces",
        args: &[Arg::Node, Arg::Faces, Arg::Param("translation")],
        fan: Fan::PerNode,
        refusal: "Select the faces to move",
        source: "commands.py:525 (refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.rotate_faces",
        label: "Rotate faces",
        needs: FACES,
        params: &[p("axis_point", "axis point", POINT, ""), p("axis_dir", "axis direction", POINT, ""), p("angle_deg", "angle", ANGLE, "")],
        flow: Flow::Form,
        route: "rotate_faces",
        args: &[Arg::Node, Arg::Faces, Arg::Param("axis_point"), Arg::Param("axis_dir"), Arg::Param("angle_deg")],
        fan: Fan::PerNode,
        refusal: "Select the faces to rotate",
        source: "commands.py:528 (refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.set_radius",
        label: "Set cylinder radius",
        needs: FACES,
        params: &[p("radius", "radius", LENGTH, "")],
        flow: Flow::Form,
        route: "set_radius",
        args: &[Arg::Node, Arg::Face, Arg::Param("radius")],
        refusal: "Select a cylindrical face",
        source: "commands.py:531 (the first selected face; refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.untrim",
        label: "Untrim faces",
        needs: FACES,
        route: "untrim",
        args: &[Arg::Node, Arg::Faces],
        fan: Fan::PerNode,
        refusal: "Select the faces to untrim",
        clears_selection: true,
        source: "commands.py:559 (delete_faces; the selection cleared as tool.delete_face's; refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.array_curve",
        label: "Array along curve",
        needs: Needs::NodesThenPath,
        params: &[p("count", "count", count_from(2.0), ""), p("align", "align to the path", CHECK, "true"), p("as_instances", "As live instances", CHECK, "false"), p("merge", "Merge into one body", CHECK, "false")],
        flow: Flow::Form,
        route: "array_curve",
        args: &[Arg::AllButLast, Arg::Last, Arg::Param("count")],
        kwargs: &[("align", Arg::Param("align")), ("as_instances", Arg::Param("as_instances")), ("merge", Arg::Param("merge"))],
        refusal: "Select the bodies, then the path curve or sketch",
        source: "commands.py:743 (align True, as_instances False, merge False; count has no default and divides by count - 1, so at least 2; refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.extract_components",
        label: "Extract components",
        needs: nodes(1, Some(1), &[]),
        params: &[p("components", "components {name: [solid indices]}", JSON, "")],
        flow: Flow::Form,
        route: "extract_components",
        args: &[Arg::Node, Arg::Param("components")],
        kwargs: &[("expected_revision", Arg::Revision)],
        refusal: "Select the one body to extract components from",
        source: "commands.py:826 (indices from GET /nodes/{id}/solids at expected_revision: a REST run must pass the revision it read them at; a form sends the revision it opened at; refusal ours)",
        ..BASE
    },
    OpEntry {
        id: "ops.set_control_points",
        label: "Set control points",
        category: "Advanced",
        needs: FACES,
        params: &[p("points", "control points [[[x, y, z], …], …]", JSON, "")],
        flow: Flow::Form,
        route: "set_control_points",
        args: &[Arg::Node, Arg::Face, Arg::Param("points")],
        refusal: "Select a face",
        source: "commands.py:864 (the first selected face; the grid tool.control_points shows); the route needs api.py's ArgConverter to pass nested `points` ([[[x, y, z], …], …]) through unconverted (that fix is in cad/robocad/api.py)",
        ..BASE
    },
];
