import assert from 'node:assert/strict';import {motionCommandConfig,motionHeartbeatIndex,nextMotionAction,boundedInputValue,driveMotionValues} from '../viewer/motion-commands.mjs';
const awkward={lower:-0.041098926819874794,upper:0.041098926819874794};
const rounded=Number(awkward.lower.toPrecision(15));assert(rounded<awkward.lower);
assert.equal(boundedInputValue(awkward,rounded),awkward.lower);
assert.equal(boundedInputValue(awkward,-rounded),awkward.upper);
assert.equal(boundedInputValue(awkward,0),0);
assert.equal(boundedInputValue(awkward,.02),.02);
assert.throws(()=>boundedInputValue(awkward,NaN));
assert.throws(()=>boundedInputValue({lower:1,upper:-1},0));
const names=['forward','lateral','yaw'],channels=names.map((name,i)=>({name,kind:i===2?'AngularVelocity':'LinearVelocity',lower:-1,upper:1}));
assert.equal(motionCommandConfig({},channels),null);
assert.deepEqual(motionCommandConfig({motion_commands:names},channels).command_channels,names);
assert.throws(()=>motionCommandConfig({motion_commands:['forward','forward','yaw']},channels));
assert.throws(()=>motionCommandConfig({motion_commands:names},channels.map(c=>({...c,kind:'Angle'}))));
assert.throws(()=>motionCommandConfig({motion_commands:names},channels.map(c=>({...c,lower:.1}))));
const existing={command_channels:names,sequence:{}};assert.equal(motionCommandConfig({data:{policy_contract:{step_reference:{config:existing}}}},channels),existing);
console.log('motion command mapping checks passed');
const hc=[...channels,{name:'packet',kind:'Dimensionless',lower:0,upper:1000,initial:0}],preset={motion_commands:names,motion_heartbeat:'packet'};
assert.equal(motionHeartbeatIndex(preset,hc),3);
const values=[1,0,0,0];assert.deepEqual(nextMotionAction(preset,hc,values),[1,0,0,1]);assert.deepEqual(values,[1,0,0,0]);
assert.deepEqual(nextMotionAction({},channels,values.slice(0,3)),values.slice(0,3));
assert.throws(()=>nextMotionAction(preset,hc,[1,0,0,1000]));
assert.throws(()=>motionHeartbeatIndex({...preset,motion_heartbeat:'forward'},hc));
console.log('motion packet freshness checks passed');
const tuned={motion_commands:names,motion_key_vectors:{w:[.23,0,.1],s:[-.23,0,-.1],a:[0,0,.2],d:[0,0,-.2]}};
assert.deepEqual(driveMotionValues(tuned,channels,new Set(['w'])),[.23,0,.1]);
assert.deepEqual(driveMotionValues(tuned,channels,new Set()),[0,0,0]);
assert.deepEqual(driveMotionValues(tuned,channels,new Set(['w','s'])),[0,0,0]);
assert.deepEqual(driveMotionValues(tuned,channels,new Set(['w','d'])),[.23,0,-.1]);
assert.deepEqual(driveMotionValues({motion_commands:names},channels,new Set(['w','a'])),[1,0,1]);
assert.throws(()=>driveMotionValues({...tuned,motion_key_vectors:{...tuned.motion_key_vectors,w:[2,0,0]}},channels,new Set()));
assert.throws(()=>driveMotionValues({...tuned,motion_key_vectors:{w:[0,0,0]}},channels,new Set()));
console.log('tuned WASD requests and legacy mapping checks passed');
