[package]
name = "sim-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
bevy.workspace = true
nalgebra.workspace = true
sim-core = { path = "../sim-core" }
sim-domain-multibody = { path = "../sim-domain-multibody" }
sim-domain-robot = { path = "../sim-domain-robot" }
sim-phenomena = { path = "../sim-phenomena" }
clap.workspace = true
