import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';
const here=import.meta.dirname,root=path.resolve(here,'../../../../..'),cases=JSON.parse(fs.readFileSync(path.join(here,'results/summary.json'))),results=[];assert.equal(cases.length,8);
for(const c of cases){const dir=path.join(here,'results',c.name),r=spawnSync(path.join(root,'target/debug/examples/review_fpga_batch'),[dir+'/uart.hex',dir+'/review.json','--sampled-two'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const j=JSON.parse(fs.readFileSync(dir+'/review.json')),direct=JSON.parse(fs.readFileSync(dir+'/events.json'));
 const retained=new Set(j.frames.map(f=>f.frame));const kinds={Telemetry:0,Control:1,Audit:2};
 assert.deepEqual(j.events.filter(e=>e.kind in kinds).map(e=>({frame:e.frame,kind:kinds[e.kind],id:e.motor_id,request:e.request_ticks,completion:e.completion_ticks})),direct.filter(e=>retained.has(e.frame)));
 if(c.scenario===0){assert.equal(direct.length,175);assert.deepEqual([...retained],Array.from({length:13},(_,i)=>i*2));assert.equal(j.sampled_capture.intentionally_unlogged_frames.length,12);assert.equal(j.terminal_result,0);}else assert.notEqual(j.terminal_result,0);
 results.push({case:c.name,retained_frames:j.frames.length,control_cycles:direct.filter(e=>e.kind===1).length,terminal_result:j.terminal_result,stats:c.stats});
}
const logger=fs.readFileSync(path.join(here,'results/logger-tests.log'),'utf8');for(const mode of [0,1])assert(logger.includes(`PASS frame logger mode ${mode}:`));
const rust=fs.readFileSync(path.join(here,'results/rust-tests.log'),'utf8');for(const n of [3,5,8,10])assert(rust.includes(`test result: ok. ${n} passed; 0 failed`));
const synthesis=fs.readFileSync(path.join(here,'results/full-image-synthesis.log'),'utf8');assert(synthesis.includes('End of script.')&&synthesis.includes('Found and reported 0 problems.'));assert(!/implicitly declared|used but has no driver/.test(synthesis));const stats=synthesis.slice(synthesis.lastIndexOf('=== top ==='));const luts=[...stats.matchAll(/^\s+(\d+)\s+LUT[1-4]\s*$/gm)].reduce((s,m)=>s+Number(m[1]),0);assert(luts>0&&luts<=23040);
const work=fs.readFileSync(path.join(here,'results/workspace.txt'),'utf8').trim();for(const file of fs.readdirSync(path.join(here,'firmware/src')))assert.deepEqual(fs.readFileSync(path.join(here,'firmware/src',file)),fs.readFileSync(path.join(work,'src',file)));
const hashes={};function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(e.name!=='verification.json')hashes[path.relative(root,p)]=createHash('sha256').update(fs.readFileSync(p)).digest('hex');}}walk(here);
for(const rel of ['crates/sim-runtime/src/controller_refinement/fpga_batch.rs','crates/sim-runtime/src/controller_refinement/fpga_events.rs','crates/sim-runtime/tests/fpga_sampled_capture.rs'])hashes[rel]=createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
fs.writeFileSync(path.join(here,'results/verification.json'),JSON.stringify({simulation_only:true,logging_stride:2,control_hz:400,normal_logging_hz:200,steady_state_logging_bits_s:226*200*10,host_link_utilization:0.452,full_controller_evidence:false,whole_image_luts:luts,device_luts:23040,rust_tests_passed:26,cases:results,sha256:hashes},null,2));console.log('PASS: alternate-frame capture, all control cycles, fault retention, strict legacy audit, 26 Rust tests, synthesis budget and source hashes');
